### ISSUE TITLE
Release notes for @actions/github 1.0.1

### ISSUE THREAD

**Issue by xt0rted** [actions/toolkit#104]
[I just got a PR](https://github.com/xt0rted/block-autosquash-commits-action/pull/37) from dependabot bumping `@actions/github` to version `1.0.1` but there doesn't seem to be release notes for this [in the project folder](https://github.com/actions/toolkit/blob/master/packages/github/RELEASES.md), or a [release/tag](https://github.com/actions/toolkit/releases). Is there an easier way to see what changed than looking through the commits?

**Comment by damccorm** [comment]
Whoops, sorry forgot to update the release notes - they should be updated now, it included a small change to enable simpler webpack configs (#101).

**Comment by xt0rted** [comment]
Same issue with the 1.1.0 releases.

**Comment by damccorm** [comment]
Updated, sorry about that - will get better at this

**Comment by xt0rted** [comment]
There's also a 1.1.0 update for `@actions/core`, are there any changes to that beside #98?

**Comment by damccorm** [comment]
No, that's it. Will update there as well

**Comment by xt0rted** [comment]
@damccorm I was looking into this more and what I found is because this is a mono repo the `package.json` of each package needs to be modified like so:

```diff
   "repository": {
     "type": "git",
-    "url": "git+https://github.com/actions/toolkit.git"
+    "url": "git+https://github.com/actions/toolkit.git",
+    "directory": "packages/github"
   },
```

Then `RELEASES.md` renamed to `RELEASE.md` or `CHANGELOG.md` ([as per dependabot](https://github.com/dependabot/dependabot-core/blob/35afcd3efa13e9c1bfe04edfd4461223b1681c0a/common/lib/dependabot/metadata_finders/base/changelog_finder.rb#L21)).

That should then allow Dependabot to pull the correct change log for each package instead of showing a [list of commits](https://github.com/xt0rted/slash-command-action/pull/4) like it's doing now. I was going to PR the changes but wasn't sure if you wanted them made.

**Comment by bryanmacfarlane** [comment]
>  I was going to PR the changes but wasn't sure if you wanted them made.

We would gladly accept a PR.

**Comment by xt0rted** [comment]
This change is in #143

**Comment by xt0rted** [comment]
The change log is showing in Dependabot's PRs now https://github.com/xt0rted/block-autosquash-commits-action/pull/44
