### ISSUE TITLE
The step to push the release branch should be more explicit.

### ISSUE THREAD

**Issue by JJ** [actions/toolkit#115]
I'm following instructions in the walk-through, but I get:

```
Download action repository 'JJ/testing-actions@releases/v1'
##[warning]Failed to download action 'https://api.github.com/repos/JJ/testing-actions/tarball/releases/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 15.233 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/JJ/testing-actions/tarball/releases/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 13.093 seconds before retry.
```

The documentation gives the impression that you just need to push to master.

It looks like the tarball is created automatically for the branch; but the step of uploading (through push -u origin) is not mentioned explicitly either.

**Comment by damccorm** [comment]
I'm a little confused - where did you get blocked in the walkthrough? We say to create a branch, that should be all you need

**Comment by JJ** [comment]
Just adding a 

    git push -u releases/v1 master

or explaining that what is actually downloaded is a .tar.gz created automatically by github from the content of the branch (or tag) would have helped.

**Comment by damccorm** [comment]
Does #119 look right?

I think I'd rather avoid explaining the tar.gz process, IMO that's an implementation detail that the author shouldn't need to know about.

**Comment by JJ** [comment]
Looks fine. Thanks!
