### ISSUE TITLE
API to get temp directory

### ISSUE THREAD

**Issue by Fabien-Chouteau** [actions/toolkit#116]
It would useful for actions to have a reliable way to get a path to the temp directory.

In tool-cache a `tempDirectory` path is computed from various parameters but this is not available in the exported API.

**Comment by damccorm** [comment]
You can use `process.env['RUNNER_TEMP']` - curious as to why you need this though

**Comment by Fabien-Chouteau** [comment]
Thank you @damccorm ,

> You can use `process.env['RUNNER_TEMP']`

Cache-tool has a much more complex way of finding the temp forlder, I figured there must be a reason and `process.env['RUNNER_TEMP']` was not reliable enough.

> curious as to why you need this though

I wrote an action to setup a tool that is in development. I need to check-out the sources and build it, and I don't want to pollute the current directory with that.

**Comment by damccorm** [comment]
> Cache-tool has a much more complex way of finding the temp forlder, I figured there must be a reason and process.env['RUNNER_TEMP'] was not reliable enough.

Yeah, we should get rid of that actually. There was a period of time during development when some of those env variables were a little shaky as we settled on patterns. Now that we're fully in production they're reliable though.

> I wrote an action to setup a tool that is in development. I need to check-out the sources and build it, and I don't want to pollute the current directory with that.

Cool, makes sense.
