### ISSUE TITLE
Change of DRAF state of Pull Request not possible over graphql

### ISSUE THREAD

**Issue by WebDucer** [actions/toolkit#1165]
**Describe the bug**

Currently, it is not possible to change the DRAFT state of the Pull Request over actions.

1. REST API have no possibility for this
2. GraphQL provide mutations for this (`convertPullRequestToDraft` and `markPullRequestReadyForReview`)
    - Normal user in GraphQL Explorer with user token: this works
    - Executing mutations from action, fails with `Resource not accessible by integration`
    - Creation of PR from action works like expected (event with draft flag)

**To Reproduce**

1. Create own action, that switch PR to draft or back
2. Trigger the action with workflow (e.g. `pull_request`)
3. DRAFT flag is not changed, action fail with error

```typescript
export async function run(): Promise<void> {
...
    const toDraft = `mutation {
      convertPullRequestToDraft(input: {pullRequestId: "${id}"}) {
        pullRequest{
          id
          number
          isDraft
          title
        }
      }
    }`


    const draftResult = await github.getOctokit(token).graphql<PullRequestChange>(toDraft)
...
}
```

**Expected behavior**

The change of the DRAFT state should be also possible from a custom action

**Additional context**

Test repository with simple action, that should change the DRAFT flag on labeling the PR
- https://github.com/Richter-Consulting/graphqp-tests/runs/7997695424

**Comment by cotty669** [comment]
Adding these permissions to the yaml resolved it for me (.jobs._$jobname_.permissons):
pull-requests: write
contents: write
