### ISSUE TITLE
Add ability to mock out process.stdout calls

### ISSUE THREAD

**Issue by jeffrafter** [actions/toolkit#118]
Currently `issueCommand` always outputs to `stdout` here: https://github.com/actions/toolkit/blob/master/packages/core/src/command.ts#L25. This is great but when writing tests for actions it quickly fills up the logs:

```
> @ test /Users/njero/Code/Examples/example-github-action-typescript
> jest

 PASS  .github/actions/debug-action/__tests__/debug.test.ts
  debug action debug messages
    ✓ outputs a debug message (5ms)

##[debug]👋 Hello! You are an amazing person! 🙌
##[debug]👋 Hello! You are an amazing person! 🙌
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.423s
Ran all test suites.
```

If the output was wrapped in a call on the `Command` object itself then it could be mocked in the jest setup. Additionally this might pave the way for alternate logging outputs down the road.

**Comment by jeffrafter** [comment]
It is also possible to mock this globally in the `jest.config.js`:

```js
const processStdoutWrite = process.stdout.write.bind(process.stdout)
process.stdout.write = (str, encoding, cb) => {
  // Note: this will soon change to ::
  if (!str.match(/^\#\#/)) {
    return processStdoutWrite(str, encoding, cb)
  }
}
```

**Comment by bryanmacfarlane** [comment]
Thanks for logging this issue!  We will implement this (we also take PRs ;) )

**Comment by xt0rted** [comment]
These log messages from tests are now causing annotations to be created when they shouldn't be. You can see an example of this in my most recent action run here https://github.com/xt0rted/slash-command-action/pull/34/checks?check_run_id=259915650#step:8:9 and here https://github.com/xt0rted/slash-command-action/pull/34/checks?check_run_id=259915650#step:8:63.

**Comment by bryanmacfarlane** [comment]
@xt0rted - not related to mocking but I think proper annotations support will fix your issue.  I can prioritize the first half of that work (ensuring logging warning / error output doesn't create an annotation).  That's a bug and I can fix.  Sound ok?  https://github.com/actions/toolkit/issues/186

**Comment by xt0rted** [comment]
@bryanmacfarlane I meant to post that on #163, both issues a pretty similar in their end goal.

**Comment by ericsciple** [comment]
would mocking the command module make more sense?

**Comment by ericsciple** [comment]
[Example here](https://github.com/actions/checkout/blob/master/__test__/retry-helper.test.ts) where core is mocked out specifically to capture info.

[Example here](https://github.com/actions/checkout/blob/master/__test__/input-helper.test.ts) where core is mocked out to control the function results.

Users can leverage mocking tools to fit their specific needs.

**Comment by jasonkarns** [comment]
@ericsciple I don't think it's just as simple as mocking core. I'm using the tool-cache module and getting all the debug messages triggered by tool-cache. I can't mock @actions/core because tool-cache has its own copy of the module. (@actions/core isn't de-duped in my node_modules tree; but even if it were, that would be a pretty fragile mock to assume they would _always_ de-dupe)

**Comment by ericsciple** [comment]
@jasonkarns good point regarding dedupe

**Comment by bryanmacfarlane** [comment]
This is what we do in setup-go tests to mock it.

https://github.com/actions/setup-go/blob/master/__tests__/setup-go.test.ts#L49

**Comment by thboop** [comment]
Closing this as workarounds are identified and we are unlikely to add it to the toolkit in the near future.
