### ISSUE TITLE
Update the `set-output` command (deprecation warning)

### ISSUE THREAD

**Issue by jsoref** [actions/toolkit#1205]
Originally filed in https://github.com/actions/upload-artifact/issues/351
https://github.com/actions/toolkit/blob/b00a9fd033f4b30f2355acd212f531ecbbb9b38f/packages/core/src/core.ts

**Describe the bug**
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**To Reproduce**
What would you like to be added?
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
When using this Action in a Workflow, GitHub displays a warning:

The `set-output` command is deprecated and will be disabled soon.

**Expected behavior**
No warnings.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yukha-dw** [comment]
Is it fixed? I've received same warning message since https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mrienstra** [comment]
Closed by https://github.com/actions/toolkit/pull/1178
Released in [`@actions/core` `1.10.0`](https://github.com/actions/toolkit/pull/1187)
