### ISSUE TITLE
Can actions merge a pull request?

### ISSUE THREAD

**Issue by thomaseizinger** [actions/toolkit#121]
Not sure if this is the right place to open this issue but it seems to be the only git related action that is currently available.

So the question is: can actions _merge_ a pull request? Is there going to be a plugin for runners that allows this?

**Comment by JasonEtco** [comment]
@thomaseizinger 👋 Yep, Actions can merge a pull request! You do it via the GitHub API, [`PUT /repos/:owner/:repo/pulls/:pull_number/merge`](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button). If you're using this library, you would do something like this, using [`octokit.pulls.merge`](https://octokit.github.io/rest.js/#octokit-routes-pulls-merge):

```js
const { GitHub } = require('@actions/toolkit')
const octokit = new GitHub(process.env.GITHUB_TOKEN)
await octokit.pulls.merge({
  owner,
  repo,
  pull_number
})
```

Hope that helps! I'll close this issue, but feel free to reopen if you have further questions on this.

**Comment by thomaseizinger** [comment]
Ah yes, of course!
Awesome, thanks :)
