### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by pboling** [actions/toolkit#1214]
While Github staff have pushed a few commits over the last few months, and corrected some documentation, there has been little engagement with the community in the issue tracker and pull requests.

The question must be asked, _is Github Actions an ongoing concern for Github_?

Please do the following: Sort the [issues list by "Most Commented"](https://github.com/actions/toolkit/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc), find the issue that has an **order of magnitude** more comments than everthing else, read the hundreds of comments, understand the issue, and then respond to the issue.  The initial response from Github was years ago, and showed a complete (🤦 ) lack of understanding of the issue, so please don't do that again.  Since that initial response it has been utterly ignored by Github.

<img width="1368" alt="Screen Shot 2022-10-15 at 6 27 47 AM" src="https://user-images.githubusercontent.com/19505/195957408-dd8b59b3-00ab-4b8a-800a-8c47cb9fb704.png">

**Comment by fguisso** [comment]
Just comment to follow the thread and say that I use this a lot toolkit and I have probably 10 Github Actions using a bash script and I'm porting everything to use the toolkit. It's essential for me to know the future of the project.

**Comment by pboling** [comment]
The original issue has been closed, and all discussion apparently belongs in the [Community Discussion](https://github.com/orgs/community/discussions/15452), in spite of the fact that GitHub has a non-existent track record of responding to Community Discussions.  Reminds me of Apple's Community Discussions...

Anyways, closing this.
