### ISSUE TITLE
tool-cache extractZipWin does not support older PowerShell versions if file name does not end in .zip

### ISSUE THREAD

**Issue by Vampire** [actions/toolkit#1287]
It seems if the tool-cache `extractZip` function is used on a self-hosted runner where only PowerShell 5.1 or similar is available, it fails to extract the file if it does not end in `.zip` as the `Expand-Archive` cmdlet complains that it only supports files named `....zip`.

It would be nice if the tool-cache `extractZip` function would mitigate this issue so that not all actions using it need to be "fixed".
It could for example always rename (and later rename back) or copy the file to fit the naming restriction before expanding it. Or maybe only if an powershell version that has this requirement is detected or similar.

**Comment by lukka** [comment]
This is a dup of the older https://github.com/actions/toolkit/issues/1179
