### ISSUE TITLE
cacheUtils.getCompressionMethod broke with zstd 1.5.4

### ISSUE THREAD

**Issue by parched** [actions/toolkit#1341]
The windows-2022 runners have just updated to zstd v1.5.4, this changes [the string](https://github.com/facebook/zstd/commit/9c93dd71cdb301595a8a9e364348967a173c010c) that is used to [detect zstd](https://github.com/actions/toolkit/blob/d2b7d85e7cb61467395604aae1b84439c320cb84/packages/cache/src/internal/cacheUtils.ts#L100).
This causes a cache miss on this runner.

**Comment by kleisauke** [comment]
FWIW, this is also causing issues in actions/cache: https://github.com/actions/cache/issues/1110.
