### ISSUE TITLE
Cache Not Matching:  One or more cache(s) with similar key but they have different version or scope

### ISSUE THREAD

**Issue by rplankenhorn** [actions/toolkit#1376]
**Describe the bug**
When using the `@actions/cache` package, I am unable to restore caches created using the exact same running on subsequent runs.

```
##[debug]No matching cache found for cache key 'javascript-Linux-X64-asdf-cache-v3-ad0714eded685c1468e724c55d2e35a406f19927fb887e51f50439fb6ce03afb', version '8f2c4c9871d15fb24bd9c7ff48a327b81a4ae937f38daeb3e64228538586e821 and scope refs/heads/main. There exist one or more cache(s) with similar key but they have different version or scope. See more info on cache matching here: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key 
##[debug]Other caches with similar key:
##[debug]Cache Key: javascript-Linux-X64-asdf-cache-v3-ad0714eded685c1468e724c55d2e35a406f19927fb887e51f50439fb6ce03afb, Cache Version: 70108c5493886eef63e4ea83249a420f4e651fe696[22](https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4451018370/jobs/7817280641#step:3:23)5cdb3e6597dca83b6a5d, Cache Scope: refs/heads/main, Cache Created: 20[23](https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4451018370/jobs/7817280641#step:3:24)-03-17T19:47:06.9966667Z
##[debug]Failed to delete archive: Error: ENOENT: no such file or directory, unlink ''
```

**To Reproduce**
1. Go to https://github.com/rplankenhorn/github-actions-cache-issue
2. Click on Actions, Javascript, Added JS Action
3. Click Rerun All Jobs
4. Observe error for both ubuntu-latest and macos-latest runners.

**Expected behavior**
Cache should be matched and restored.

**Screenshots**
<img width="1316" alt="Screenshot 2023-03-17 at 3 52 19 PM" src="https://user-images.githubusercontent.com/228338/226016014-64af4b84-fc8f-4175-b548-abc1b323b217.png">

**Additional context**
Note:  Caching works as expected when using the published `@action/save` and `@action/restore`.

**Comment by rplankenhorn** [comment]
@MSP-Greg Thanks for getting back to me and good catch.  I made the changes [here](https://github.com/rplankenhorn/github-actions-cache-issue/commit/3b41603f137b70bc2ceb33b5c67ab963589e0501) but the cache is still not matching.  I completely deleted all the cache, recreated them, and then ran the job a third time to try and restore them:  https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4480149929/jobs/7875080489

```
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/MceA4re36QTIzQw93oLEwLlynmegnm6Wy6zMkqz54Pugm4WIPJ/_apis/artifactcache/cache?keys=javascript-Linux-X64-asdf-cache-ad0714eded685c1468e724c55d2e35a406f19927fb887e51f50439fb6ce03afb&version=70108c5493886eef63e4ea83249a420f4e651fe696225cdb3e6597dca83b6a5d
Cloning into '/home/runner/.asdf'...
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/MceA4re36QTIzQw93oLEwLlynmegnm6Wy6zMkqz54Pugm4WIPJ/_apis/artifactcache/caches?key=javascript-Linux-X64-asdf-cache-ad0714eded685c1468e724c55d2e35a406f[19](https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4480149929/jobs/7875080489#step:3:20)927fb887e51f50439fb6ce03afb
##[debug]No matching cache found for cache key 'javascript-Linux-X64-asdf-cache-ad0714eded685c1468e724c55d2e35a406f19927fb887e51f50439fb6ce03afb', version '70108c5493886eef63e4ea83249a4[20](https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4480149929/jobs/7875080489#step:3:21)f4e651fe696225cdb3e6597dca83b6a5d and scope refs/heads/main. There exist one or more cache(s) with similar key but they have different version or scope. See more info on cache matching here: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key 
##[debug]Other caches with similar key:
##[debug]Cache Key: javascript-Linux-X64-asdf-cache-ad0714eded685c1468e724c55d2e35a406f19927fb887e51f50439fb6ce03afb, Cache Version: 2e300497d0ee7c7058a03dff2243903148a762c27b17b76a2d7d5c1782ee4e98, Cache Scope: refs/heads/main, Cache Created: 2023-03-[21](https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4480149929/jobs/7875080489#step:3:22)T14:21:29.39Z
##[debug]Failed to delete archive: Error: ENOENT: no such file or directory, unlink ''
```

As you can see, still getting the same error.  Here is the link to the full job: https://github.com/rplankenhorn/github-actions-cache-issue/actions/runs/4480149929/jobs/7875080489

**Comment by MSP-Greg** [comment]
Can you try changing:
```js
const cacheId = restoreCache(cachedPaths, primaryKey);
```
to
```js
const cacheId = restoreCache(cachedPaths.slice(), primaryKey);
```

**Comment by rplankenhorn** [comment]
@MSP-Greg I was able to resolve the above error and now cache is restoring properly.  So passing in a shallow copy of the array rather than the array itself is what fixed the issue?  Should the restore/save functions be updated to automatically handle this for the user?

**Comment by MSP-Greg** [comment]
> So passing in a shallow copy of the array rather than the array itself is what fixed the issue?

Yes.  It should be an array of strings, so I think `slice()` works for all cases.

> Should the restore/save functions be updated to automatically handle this for the user?

See PR #1378

**Comment by rplankenhorn** [comment]
Duplicate of #1377
