### ISSUE TITLE
Workflow badges return 404

### ISSUE THREAD

**Issue by klingtnet** [actions/toolkit#144]
I was not able to configure a badge as described [in the documentation](https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository). The `badge.svg` resource always returns 404, either for the [example](https://github.com/actions/hello-world/workflows/.github/workflows/main.yml/badge.svg) or for [the one I tried to setup](https://github.com/klingtnet/toolbelt/workflows/go/badge.svg).

**Comment by xt0rted** [comment]
The workflow name is case sensitive, try using `https://github.com/klingtnet/toolbelt/workflows/Go/badge.svg`.

![badge](https://github.com/klingtnet/toolbelt/workflows/Go/badge.svg)
