### ISSUE TITLE
Missing `types` field in `package.json`

### ISSUE THREAD

**Issue by demurgos** [actions/toolkit#148]
The `package.json` files have a `main` field but are missing a `types` field, it prevents some editors (such as Jetbrains' Webstorm and Intellij) from picking the type declarations and providing autocompletion.

For example, for `@actions/core`, the `package.json` should look like this:

```json
{
  "name": "@actions/core",
  "main": "lib/core.js",
  "types": "lib/core.d.ts"
  // ...
}
```

**Comment by demurgos** [comment]
I found that the error was on my end, I was using the Typescript options `allowSyntheticDefaultImports` and `esModuleInterop` with default imports (instead of star imports) while the modules are marked as transpiled from Typescript. After switching to star imports, it works. It may still be a good thing to add the `types` field but it's less important.

**Comment by bryanmacfarlane** [comment]
In addition actions should have dev dependency on types: 
https://github.com/actions/javascript-action/blob/master/package.json#L26

But yeah, looks like a good thing to set per docs:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
