### ISSUE TITLE
Artifact upload speeds are artificially bottle necked to 8 MB chunks

### ISSUE THREAD

**Issue by StephenHodgson** [actions/toolkit#1533]
https://github.com/actions/toolkit/blob/c5c786523e095ca3fabfc4d345e16242da34e108/packages/artifact/src/internal/shared/config.ts#L4

https://github.com/actions/toolkit/blob/c5c786523e095ca3fabfc4d345e16242da34e108/packages/artifact/src/internal/upload/blob-upload.ts#L33

Any idea if this is an arborary choice, or a way to better calculate or set this value to remove the upload artifact bottlenecks?

See https://github.com/actions/upload-artifact/issues/403

**Comment by loiclefevre** [comment]
Solved _partially_ by first zipping files into an archive (see shell command below) and then asking to upload this archive:

`find . | grep -E '(/path1/|/path2/)' | zip -9q ${ZIP_NAME}.zip -@`

Yes, it results in a zip containing a zip file but my upload process went from 18 minutes down to 22 sec for 550 MB of data contained in 5000+ files.

**Comment by StephenHodgson** [comment]
I also already use pre zipped method, but insufferably slow

**Comment by casanova-21** [comment]
Hi, team. Is there any update on the work to fix this? I have a customer also running into this problem. They've tried the pre-zip method which doesn't have any impact on the amount of time it takes to upload their artifacts.

**Comment by prplecake** [comment]
Pretty soon Copilot will be artificially limiting upload speeds for us!

**Comment by StephenHodgson** [comment]
v4 fixes perf issues, thanks team!
