### ISSUE TITLE
Would github write a official ssh deploy actions,third party isn't good enough

### ISSUE THREAD

**Issue by joebnb** [actions/toolkit#1543]
would github write  a offical ssh deploy action for self hosted service user?current only have self host actions,if have a deploy methods like ssh scp,it would be better.

and in action market there have plugins to do that,but it's hard to use.

like: 
https://github.com/appleboy/ssh-action/issues/80
https://github.com/easingthemes/ssh-deploy/issues/143

users are facing same errors and no one can answer or make it correct,i think if official do a plugin,just can copy and execute command on remote is fulfilled majority requirements of self hosting, pls consider

**Comment by codespearhead** [comment]
I honestly agree.

However, I estimate that about 90% of the problems stem from how to properly deal with SSH authentication in those projects, not how to use the projects themselves.

Are you willing to collaborate on a pull request?

**Comment by codespearhead** [comment]
I honestly agree.

However, I estimate that about 90% of the problems in those projects stem from how to properly establish the SSH connection, not how to use the projects themselves.

There should be a quick-start guide to those who are dealing with virtual machines in an IaaS fashion, and need to carry it out themselves: from creating the key pair to allowing SSH access.

@joebnb Are you willing to collaborate on a pull request on that at [ssh-deploy](https://github.com/easingthemes/ssh-deploy)?

**Comment by joebnb** [comment]
> I honestly agree.
> 
> However, I estimate that about 90% of the problems in those projects stem from how to properly establish the SSH connection, not how to use the projects themselves.
> 
> There should be a quick-start guide to those who are dealing with virtual machines in an IaaS fashion, and need to carry it out themselves: from creating the key pair to allowing SSH access.
> 
> @joebnb Are you willing to collaborate on a pull request on that at [ssh-deploy](https://github.com/easingthemes/ssh-deploy)?

it's seems is self hosted runner feature problem，here is my new issues https://github.com/actions/runner/issues/2904 

and today i created a local vm that was setup by ubuntu jammy, and install github actions without under docker.it's all failed.
