### ISSUE TITLE
@actions/cache mutates the `paths` argument.

### ISSUE THREAD

**Issue by ramblingenzyme** [actions/toolkit#1579]
**Describe the bug**
https://github.com/actions/toolkit/blob/main/packages/cache/src/internal/cacheHttpClient.ts#L83
This line means that the changes to the array change the array the user passes.
This breaks code such as
```js
import * as cache from "@actions/cache";

const paths = ["some/paths"];
const key = "a-key";

// This calls `getCacheVersion` internally and mutates `paths`
const cacheKey = await cache.restoreCache(paths, key);
if (cacheKey) {
  core.info(`Cache restored from key: ${cacheKey}`);
  return;
}

// At this point the variable `paths = ["some/paths", "zstd-without-long", "1.0"]`


const savedCacheKey = await cache.saveCache(paths, key);
// This means when `saveCache` calls `getCacheVersion` it was actually calculated off of the final array value: `["some/paths", "zstd-without-long", "1.0", "zstd-without-long", "1.0"]`
}
```

This means that we run into a version mismatch when restoring the cache in another step later on.

**Expected behavior**
Inputs to functions don't get mutated and break intended functionality of the library.

**Screenshots**
![image](https://github.com/actions/toolkit/assets/5336472/d15a9dc0-9d6d-437c-898f-e75f276b21b8)
This is following the hashing to create versions, with the inputs from our code, and you can see that `components2` with the compression and version salt in twice matches the version of the created caches.

**Comment by bethanyj28** [comment]
Fixed in https://github.com/actions/toolkit/pull/1378 (v3.2.3)
