### ISSUE TITLE
`@actions/artifact` dependency `crypto` is deprecated

### ISSUE THREAD

**Issue by muzimuzhi** [actions/toolkit#1614]
**Describe the bug**

Installing `@actions/artifact` gives
```
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in
Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

See also https://www.npmjs.com/package/crypto.

**To Reproduce**

Run `npm install` in `./packages/artifact`.

**Comment by pauliesnug** [comment]
I can reproduce this as well. We need to switch all `crypto.createHash('sha256')` calls to use `node:crypto`

**Comment by pngwn** [comment]
`crypto` can't be resolved when bundling either. This makes the package unusable currently.
