### ISSUE TITLE
getArtifact function using deprecated (due to security and usability issues) buffer function 

### ISSUE THREAD

**Issue by twalshOG** [actions/toolkit#1618]
**Describe the bug**
Receive a deprecation warning when using downloading an artifact

**To Reproduce**
1. Use the the downloadArtifact functionality in a Github actions pipeline
2. Note you get the following error
> (node:1671) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)

Code producing the warning
```
import * as artifact from '@actions/artifact';
.........
  const response = await artifact.default.getArtifact(artifactName);
  const artifactClient = artifact.default;
  await artifactClient.downloadArtifact(response.artifact.id, {
    path: downloadFolder,
  });

```

**Expected behavior**
Would not get the error.
This error is due to the fact that @actions/artifact is depending on [archiver 5.3.1](https://github.com/actions/toolkit/blob/5430c5d84832076372990c7c27f900878ff66dc9/packages/artifact/package.json#L52C9-L52C9) which in turn depends on archiver-utils 2.1.0 which use using the [depreciated buffer call](https://github.com/archiverjs/archiver-utils/blob/1cfa5b19955a0eeda7b17cd369d6f00362764cf7/index.js#L85). 

**Screenshots**
![Screenshot 2024-01-05 at 1 05 40 PM](https://github.com/actions/toolkit/assets/106253115/914c6c45-5241-4b0c-b05d-de198801a041)

**Where produced **
 - Github Actions Agent: ubuntu-latest
 - Node version: Default version installed on ubuntu-latest

**Additional context**
Updating to a new version ([3.0.0](https://github.com/archiverjs/archiver-utils/releases/tag/3.0.0) or above) would address this issue.
The [fix/update](https://github.com/archiverjs/archiver-utils/pull/18) to this was already released for archiver-utils.

**Comment by TWiStErRob** [comment]
To finish the amazing investigation, and give actionable steps for this project:

https://github.com/actions/toolkit/blob/5430c5d84832076372990c7c27f900878ff66dc9/packages/artifact/package.json#L52

The above line needs to be updated from 5.3.1 to at least [6.0.0](https://github.com/archiverjs/node-archiver/releases/tag/6.0.0), which doesn't look like a big jump, as the only breaking change listed is dropping Node 10.

**Comment by hubert-rutkowski85** [comment]
Bump - it seems like a simple and useful change.

**Comment by twalshOG** [comment]
This bug was addressed in https://github.com/actions/toolkit/pull/1712
