### ISSUE TITLE
how to disable core.debug in testing

### ISSUE THREAD

**Issue by tianhaoz95** [actions/toolkit#163]
Is there a way to disable `core.debug` when I am running jest locally? It is not so helpful to have all the logs on when running regression test.

**Comment by bryanmacfarlane** [comment]
The current model is for the action to emit the output and the runner to conditionally add to logs based on setting.  

Can you clarify whether you want a way to silence during E2E testing or unit testing etc...?

**Comment by tianhaoz95** [comment]
Unit testing. For a `node.js` action, locally when i run `jest --quiet`, if I have some `core.debug` in my code, it will still print out to my console. I am guessing it is because jest doesn't recognize lower level logging. Is there a way that I can set some environment variable `ACTION_LOG=false` to disable that? I know that setting GitHub action secret can do that, but is there a equivalent locally?

**Comment by xt0rted** [comment]
I think this is a duplicate of #118

**Comment by tianhaoz95** [comment]
@xt0rted I think you are right. What is the final decision? jest config or some alternative?

**Comment by ericsciple** [comment]
would mocking the core module make more sense?

**Comment by ericsciple** [comment]
[Example here](https://github.com/actions/checkout/blob/master/__test__/retry-helper.test.ts) where core is mocked out specifically to capture info.

[Example here](https://github.com/actions/checkout/blob/master/__test__/input-helper.test.ts) where core is mocked out to control the function results.

Users can leverage mocking tools to fit their specific needs.

**Comment by bryanmacfarlane** [comment]
Assigning to myself to update docs and guidance pointing to the examples ☝️

**Comment by thboop** [comment]
dupe of https://github.com/actions/toolkit/issues/163

**Comment by pbrisbin** [comment]
Sorry to bump an old issue, but I think this guidance doesn't work since `@actions/*` has moved to ESM modules.

I get,

```
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'info' of object '[object Module]'

      at node_modules/jest-mock/build/index.js:622:31
```

When I use,

```js
import * as core from "@actions/core";
import { jest } from "@jest/globals";

jest.spyOn(core, "info");
```

There are some more details in https://github.com/jestjs/jest/issues/10025. I've tried various workarounds that didn't work, and ultimately resorted to manual dependency injection.
