### ISSUE TITLE
First set-output ignored

### ISSUE THREAD

**Issue by elgohr** [actions/toolkit#168]
As seen in https://github.com/elgohr/ecr-login-action/pull/2 , the first `set-output` seems to be ignored. I wasn't able to figure out why, as I'm not able to test it without publishing test releases. Could you please help on that?

**Comment by thboop** [comment]
Hey @elgohr ,
Commands need to be the first item on their line (ignoring white-space) in order to be executed. That may be the issue you are running into, we can update the docs to make that more clear. Do you have example output from your action you could share?

**Comment by elgohr** [comment]
As the acion handles with credentials I don't have an example.
But the hint with the new line was really good. I'll try that first.

**Comment by thboop** [comment]
I'm going to close this issue for now, please let me know if you are still encountering issues and we can investigate again!
