### ISSUE TITLE
How to source shell script?

### ISSUE THREAD

**Issue by domenkozar** [actions/toolkit#170]
I want to write an action that will source a bash script to set all variables.

**Comment by bryanmacfarlane** [comment]
Do you want it to affect that actions steps or future steps in the job.  In other words, to you want it to be step or job scoped.

**Comment by bryanmacfarlane** [comment]
checking for answer to ^^.  Thanks!

**Comment by domenkozar** [comment]
In my use case, I'd like it to be job scoped (so my action can provide an enviroment).

The use case is installing https://github.com/marketplace/actions/install-nix and activating Nix installation (which sets a bunch of environment variables).

**Comment by bryanmacfarlane** [comment]
Is the set of variables known?  If you use core.setVariable it will export those variables for future steps (which run out of proc).  I admit that might be a bit fragile.

**Comment by ericsciple** [comment]
it sounds like you might want to create a javascript action that does the following:
- run `exec.exec('bash some-wrapper-script.sh')`
- in the wrapper script:
  - dot source the script supplied by the customer
  - output some delimiter so you know the customer output has ended
  - output all env vars
- capture stdout from the above invocation; use everything after the delimiter to construct a dictionary of the env var state at the end of your wrapper script
- compare the env state from the end of the wrapper script against `process.env`
- call `core.exportVariable()` for anything different
