### ISSUE TITLE
Example workflow.yml is a 404

### ISSUE THREAD

**Issue by Scrxtchy** [actions/toolkit#181]
At the bottom of the workflow setup page is are these links
![image](https://user-images.githubusercontent.com/12771982/66258006-c205c680-e7eb-11e9-8b37-4904cac43be0.png)

the workflow.yml links to this repo, but the link is dead

https://github.com/actions/toolkit/blob/master/.github/workflows/workflow.yml

it has been renamed on 1643ea2734516db5d2fe78423234cd638d5bdbb8 and not updated on the github frontend

**Comment by bryanmacfarlane** [comment]
Thanks!   I'll log an issue for the front end.

**Comment by joshmgross** [comment]
Thanks for reporting this!
That link now points to https://github.com/actions/toolkit/tree/master/.github/workflows
