### ISSUE TITLE
Support dynamic outputs

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/toolkit#185]
**Describe the enhancement**
Sometimes the number of outputs is not known in advance.  For example, if I retrieve 5 values from a store based off a wild card or list input.  

Note that forward declaring outputs is useful for driving intellisense but in the case of dynamic outputs, it's not as critical as it's not known up front.

**Code Snippet**
```yaml
   outputs: *
```

```javascript
// free to set as many outputs as you want dynamically without forward declaring
core.setOutput(key1, val1)
core.setOutput(key2, val2)
```

**Additional information**
Add any other context about the feature here.

Related to #184

**Comment by ericsciple** [comment]
i have a pr open to fix this in github.com docs. Basically it already works today. Nothing needs to be advertised in the action manifest. That is, dont do `outputs: *`, just do `core.setOutput(...)`
