### ISSUE TITLE
Extract tar.gz on windows-latest failed.

### ISSUE THREAD

**Issue by xpol** [actions/toolkit#194]
**Describe the bug**
The follow code:

```js
const tc = require("@actions/tool-cache")
tc.extractTar(tarball, SOURCE_DIRECTORY)
```

Fails to run under windows-latest (other windows version not tested).

```
"C:\Program Files\Git\usr\bin\tar.exe" xz -C d:\a\install-lua\install-lua\.source\ -f d:\a\_temp\5e8814d7-8526-46bd-bd88-ed84e58259a1
tar (child): Cannot connect to d: resolve failed

gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
##[error]Failed to install Lua: Error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
##[error]Node run failed with exit code 1
```

**To Reproduce**
1. Use extractTar in actions scripts.
2. Run the action on windows latest

**Expected behavior**

Show extractTar correctly on windows.

**Comment by JJ** [comment]
You are trying to access unit d: Is that automatically created or is it a part of your action? The error says it's not finding it.

**Comment by ericsciple** [comment]
discussing a fix on pr https://github.com/actions/toolkit/pull/165

**Comment by ericsciple** [comment]
@xpol also curious about the scenario. Many tools offer multiple archive formats for users on different platforms (zip or 7z for windows)

**Comment by ericsciple** [comment]
And the `tar` command doesnt exist on older versions of windows (which are supported by self hosted runners)

**Comment by ericsciple** [comment]
fixed with https://github.com/actions/toolkit/pull/264
