### ISSUE TITLE
Linking annotations back to the log lines

### ISSUE THREAD

**Issue by jimhester** [actions/toolkit#202]
When you use a problem matcher to create annotations and don't supply a file or line, it would be useful if it would link to the line in the log where the annotation occurred, rather than just linking to the commit. e.g.

![Screen Shot 2019-11-06 at 9 29 59 AM](https://user-images.githubusercontent.com/205275/68306719-0ea52180-0078-11ea-8c1a-cb58dc6b3d30.png)

This screenshot is from (https://github.com/jimhester/r-actions-test/runs/291007383)

The errors and warnings we get when checking R packages don't typically have a specific source file or line attached, so this is a common case for us.

Apologies if this is not the best place for this issue, I wasn't sure if I should open it here or on the community site.

**Comment by bryanmacfarlane** [comment]
This should go to the community site since it's actually an issue with the service and not the toolkit.  The runner sends up with a log link and line number but it's not getting represented correctly.

**Comment by bryanmacfarlane** [comment]
Feel free to shoot me a note with with the community post and I'll pass it along to the right folks.

**Comment by jimhester** [comment]
Ok, thanks for replying, I posted on community at https://github.community/t5/GitHub-Actions/Linking-annotations-back-to-the-log-lines/m-p/37875#M3110

**Comment by bryanmacfarlane** [comment]
Sent.  Thank you.
