### ISSUE TITLE
Trailing comma in `::set-output``

### ISSUE THREAD

**Issue by hvr** [actions/toolkit#208]
I'm not sure if this is relevant, but I noticed that the log shows the meta-command

```
::set-output name=cache-hit,::true
```

being emitted, whereas based on Github actions documentation I would have expected

```
::set-output name=cache-hit::true
```

Sorry for the noise if this is in fact harmless.

**Comment by bryanmacfarlane** [comment]
Yeah, this is as designed as the , is just an empty property.  Both work.

**Comment by ericsciple** [comment]
the trailing comma is kind of silly, we should probably remove it
