### ISSUE TITLE
Can exec.exec run process in the background?

### ISSUE THREAD

**Issue by bahmutov** [actions/toolkit#216]
I am trying to test a locally running server, which means the server should be running in the background. I can run a child process in detached mode using https://github.com/sindresorhus/execa but had no luck doing it on Windows unfortunately - always getting `ENOENT`.

```
found command "C:\Program Files\nodejs\npm.cmd"
with arguments start
child process unref
Running Cypress tests
Cypress test command: npx cypress run --record --parallel --ci-build-id "Using Cypress GH Action - 0b1506a25525bea98c3ca9e8e4291717d1747eff" --group "Parallel 2x on windows-latest"
C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npx.cmd" cypress run --record --parallel --ci-build-id """Using Cypress GH Action - 0b1506a25525bea98c3ca9e8e4291717d1747eff""" --group """Parallel 2x on windows-latest""""
(node:852) UnhandledPromiseRejectionWarning: Error: spawn "C:\Program Files\nodejs\npm.cmd" ENOENT
    at notFoundError (d:\a\_actions\cypress-io\github-action\0bb1882\dist\index.js:7313:26)
    at verifyENOENT (d:\a\_actions\cypress-io\github-action\0bb1882\dist\index.js:7347:16)
    at ChildProcess.cp.emit (d:\a\_actions\cypress-io\github-action\0bb1882\dist\index.js:7334:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Everywhere else I am using `exec.exec` to run child processes - maybe there is a way to use `exec.exec` to run a process in the background?

**Comment by bryanmacfarlane** [comment]
Do you want to run other stuff within the scope of your step / action while this runs?  Or do you want the step to run something in the background and continue onto other steps?  (the latter is a feature we've discussed that has much broader impact beyond the toolkit).  The former may be possible with holding onto the Promise returned and running other code (since I/O isn't blocking in node) and then on promise complete, printing results.  I haven't tried - just thinking out loud.

@ericsciple for ENOENT with Program Files and cmd error

**Comment by bahmutov** [comment]
Hi @bryanmacfarlane for me, it is only a background process during the current step. Imagine it is a testing action - running end-to-end Cypress tests against a locally spawned server. Something like this:

```yml
- name: run tests
  uses: cypress-io/github-action@v1
  with:
    start: npm start
```

it starts the `npm start`, then runs tests etc. On Linux and Mac when I use `execa` I can simply unref the child process to allow my action to exit, and GitHub cleans up orphan processes

```js
const options = {
  shell: true,
  detached: true,
  stdio: 'inherit'
}
const childProcess = execa(quote(toolPath), args.slice(1), options)
childProcess.unref()
```

I have used `exec.exec` without waiting on the returned promise - it works, but the process then hangs waiting for the child process to exit. Maybe allow `detached` flag in the `exec.exec` options to `cp.unref`?

As a workaround now I explicitly call `process.exit(0)` after the tests finish, which let's GH clean up

```
Complete job0s
Terminate orphan process: pid (1404) (node)
Cleaning up orphan processes
Terminate orphan process: pid (3664) (node)
Terminate orphan process: pid (5920) (cmd)
Terminate orphan process: pid (1404) (node)
```

**Comment by bryanmacfarlane** [comment]
Thanks for clarifying.

For the scenario of spinning up a server while testing, I would recommend the [services](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idservices) yaml feature which was implemented for this scenario.  It spins up a `side car` container for the job.  Then you can use a trivial `run:` step to run the tests as the dev does.  Caveat is you have to containerize what you're spinning up (even if just for the test).

**Comment by ericsciple** [comment]
> it is only a background process during the current step

In this case I would expect the action to be self contained.

@bahmutov the reason the process is hanging is because you set `stdio: 'inherit'`. If you set it to `stdio: 'ignore'` then you will not need the process.exit() hack. Note, nodejs (under resource scarce conditions iirc) buffers stdout. So when you call process.exit you can lose stdout from the process.

Would setting `stdio: 'ignore'` work for your scenario? Or do you desire the output to come through?

I ask because, if you desire the output, then for your scenario it would make more sense for the toolkit to offer an easy way to send CTRL+C to the process.

**Comment by ychescale9** [comment]
@bryanmacfarlane Sorry for posting after it's closed for 1 year, but has there been any progress on being able to "run something in the background and continue onto other steps"? Is there an opened issue for this feature request?

**Comment by viliusddd** [comment]
I would be 

> @bryanmacfarlane Sorry for posting after it's closed for 1 year, but has there been any progress on being able to "run something in the background and continue onto other steps"? Is there an opened issue for this feature request?

I would be interested in it too

**Comment by jldec** [comment]
I'm not sure this answers your question @ychescale9 and @viliusddd, but i have had success launching a server in a background process and then performing tests against it, within a single step on linux. The only catch is that you may need a sleep (or something similar) after launching the server to give it time to start listening.

example code in [this workflow](https://github.com/jldec/cloudflare-pages-test/blob/main/.github/workflows/generate.yaml#L27-L29) - or [blogpost](https://jldec.me/running-a-compiled-deno-script-in-a-github-action#githubworkflowgenerateyaml).

**Comment by shem8** [comment]
I have the exact same problem. I can't pass any args (like `stdio: 'ignore'`) to the exec command since the library emits unknown args from the options object.
Any idea how to running something in the background without it block the rest of the action steps?
