### ISSUE TITLE
Rewrite into Haxe

### ISSUE THREAD

**Issue by KOLANICH** [actions/toolkit#222]
**Describe the enhancement**
Haxe is a language with ECMAScript-like syntax transpiled into multiple languages, such as JS, python and java. Rewriting the toolkit in Haxe may help to port it to python.

**Comment by jclem** [comment]
Hi @KOLANICH, thank you for the suggestion! Right now, the toolkit is written in something that compiles to JavaScript, because that's guaranteed to be present in every environment supported by Actions runners. While I'm a fan of the Haxe project (I've tinkered with some game development stuff in it myself 😄 ), a rewrite isn't something we have plans for, at the moment.

I'm going to close this issue, but have a question for you—Given that a Node.js runtime is on every runner, I am still curious if you see specific benefits to a toolkit that can be compiled to various other runtimes.

**Comment by KOLANICH** [comment]
>I am still curious if you see specific benefits to a toolkit that can be compiled to various other runtimes.

The most of benefit is to staying away of node.js and npm as much as possible because npm has extremily bad reputation as plagued with malware. I don't know why pypi isn't. Anyway, I try to stay away of package registries as much as possible.

**Comment by eyal0** [comment]
@jclem So, if I write an action in Python, users of the action will need to install python to use it?

How do actions run on a caller's workflow? Does all the code get copied into the caller's VM and it runs there? Or is it installed or compiled somehow?

**Comment by jclem** [comment]
> So, if I write an action in Python, users of the action will need to install python to use it?

@eyal0 Not necessarily. The goal of the Actions Toolkit is to provide a set of tools that make it easy to write actions that will run on every runtime that we support (Ubuntu, Windows, macOS). We chose Node.js, a runtime that is also already present on the VMs that we run actions on across those operating systems. However, there are a couple of options for writing actions using things other than Node.js:

1. As you said, requiring the language to be installed by the user on the VM using something like [actions/setup-python](https://github.com/actions/setup-python). This route works well if your action is typically only used by users that are already using that language in their workflows (e.g. commonly Python for things like data science workflows).
1. Write your action using a Docker container. There is a good amount of documentation on this [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-docker-container-action).

> How do actions run on a caller's workflow? Does all the code get copied into the caller's VM and it runs there?

That's more or less it. The action is cloned to the virtual machine for that job in the workflow and runs as a standalone process there.

**Comment by xt0rted** [comment]
> 2\. Write your action using a Docker container.

@jclem this limits you to only Ubuntu vms then. When I tried running docker based actions on a Windows vm I got an error saying they weren't supported on Windows or macOS. This means js based actions are the only way to run something cross platform at the moment.

**Comment by jclem** [comment]
@xt0rted Correct, for cross-platform actions, using Node and the toolkit (if needed) are usually the easiest way to go if you don’t want to add any runtime requirements to your consumers’ workflows. 

Of course, anything that can compile to JavaScript and be run by Node.js (TypeScript, Reason, etc) will also work, and the use of the toolkit is 100% optional.

**Comment by jclem** [comment]
It’s worth noting that it’s totally not necessary to use the toolkit for the majority of the things it does. Python can of course make use of the documented [logging commands](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands).

**Comment by KOLANICH** [comment]
It is totally not necessary,  but if there is no, I would have to write an own one. But I don't want to. It'd be better if MS have written it.
