### ISSUE TITLE
Action showing up several times in "checks"

### ISSUE THREAD

**Issue by ajcann** [actions/toolkit#240]
Not sure if this is the right place. This may relate to https://github.com/actions/stale/issues/13 

In our PRs under the scenarios - 
```
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize]
```
The checks are showing up multiple times and preventing a green due to past failed checks.

<img width="720" alt="Screen Shot 2019-12-03 at 6 41 10 PM" src="https://user-images.githubusercontent.com/10137494/70177786-e406b280-168f-11ea-9657-8af74557a4c4.png">

**Comment by ajcann** [comment]
Created a public example repo here: https://github.com/ajcann/multiple-checks-issue/pull/2

**Comment by bryanmacfarlane** [comment]
Create an issue on https://github.community/

Appears to be an issue with the service and not this action toolkit
