### ISSUE TITLE
javascript-action.md broken http link

### ISSUE THREAD

**Issue by lukka** [actions/toolkit#241]
The docs mentions in multiple places to follow the instructions to this broken link:

https://github.com/actions/toolkit/blob/master/docs/javascript-action.md

**Comment by bryanmacfarlane** [comment]
Can you provide some urls that have those links?  I searched here and in the docs repo and couldn't find that url

**Comment by lukka** [comment]
e.g.: https://github.com/actions/toolkit/blob/3116829a9b8f5a5caf1d352eb209ccc7f4042b22/docs/github-package.md
