### ISSUE TITLE
building this repo on macosx fails

### ISSUE THREAD

**Issue by lukka** [actions/toolkit#242]
**Describe the bug**
Cannot build this repo on macosx.

**To Reproduce**
1. Clone the repo master branch (1c12ced7ba4b5f2d21da0ddfea83b4885505503f)
2. run 'npm -g install lerna'
2. run 'npm run bootstrap'

**Expected behavior**
Successful execution, returning exit code 0

**Screenshots**
Execution fails aborting:

````
> root@ bootstrap /Users/username/ms/git_repos/toolkit
> lerna bootstrap

lerna notice cli v3.19.0
lerna info versioning independent
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 5 packages
node[47351]: ../src/signal_wrap.cc:159:void node::DecreaseSignalHandlerCount(int): Assertion `(new_handler_count) >= (0)' failed.
 1: 0x100b8ff9a node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000832c4 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10008307c node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/bin/node]
 4: 0x1000f7e52 node::HasSignalJSHandler(int) [/usr/local/bin/node]
 5: 0x1000f85ad node::(anonymous namespace)::SignalWrap::Close(v8::Local<v8::Value>) [/usr/local/bin/node]
 6: 0x10003eb76 node::Environment::CleanupHandles() [/usr/local/bin/node]
 7: 0x10003ed2f node::Environment::RunCleanup() [/usr/local/bin/node]
 8: 0x1000b4a3a node::NodeMainInstance::Run() [/usr/local/bin/node]
 9: 0x100060f13 node::Start(int, char**) [/usr/local/bin/node]
10: 0x7fff71f8e3d5 start [/usr/lib/system/libdyld.dylib]
11: 0x3 
Abort trap: 6
````

**Desktop (please complete the following information):**
 - OS: macosx 10.14.6
 - node v13.2.0
 - npm    6.13.1

**Comment by ericsciple** [comment]
@lukka try `git clean -ffdx && npm ci && npm run bootstrap && npm run build`

**Comment by bryanmacfarlane** [comment]
Let us know if that ☝️ didn't help

**Comment by lukka** [comment]
FYI, the suggested command did not change what i am seeing.

I get exactly the same errors you get on [macos CI](https://github.com/actions/toolkit/runs/340674494)

Nevertheless, just ignoring the errors happening on both `npm ci` and `npm run bootstrap` and running `npm run build` creates successfully the packages.

**Comment by ericsciple** [comment]
I upgraded from node10 to node12 and i'm seeing errors during npm install (looks related to jest, so doesnt affect prod code)
