### ISSUE TITLE
Need a way to prevent CI

### ISSUE THREAD

**Issue by timheuer** [actions/toolkit#249]
**Describe the bug**
GitHub Actions needs a way to prevent a CI from happening based on something in the title.  Azure DevOps uses ***NO_CI*** and then the CI doesn't even start.  A few actions have been created to try to mimic this, but they still result in a CI flow starting, resources being allocatd, and then marking the workflow as failed.  GitHub Actions at it's core should have this functionality.

**Comment by bdougie** [comment]
Just stopping by for clarification and curiosity. Can you provide more details on how the check is make via the "title"?

Also interested in which actions are attempting this. Thanks

**Comment by timheuer** [comment]
@bdougie in Azure DevOps if the commit message contains "***NO_CI***" then it does not trigger a CI build.  it's kind of like a pre-kill switch.  So your commit message just contains a token of sorts -- some have done this in their own actions: https://github.com/veggiemonk/skip-commit.  I think it should be a feature of the core Actions framework.

**Comment by bryanmacfarlane** [comment]
Please request on github community.  Not an issue with the toolkit ...

**Comment by timheuer** [comment]
@bryanmacfarlane where is 'github community'?
