### ISSUE TITLE
Add Orga/User overview on GitHub Actions results/status

### ISSUE THREAD

**Issue by Apollon77** [actions/toolkit#259]
Hi,

I don't know if this is the correct repo, so please move to correct one or tell me :-)

We former used Travis-CI for all testing (nodejs applications) and we have a lot of Repos (roghly 300+). SO the good on Travis was that it was easy to have an overview on Orga and "User" (Forks) level about the current result of the Test runs, so it was easy to identify broken ones to dig into it.

Is there a way to also get such an overview for GitHub Actions of User/Orga repos?

**Comment by thboop** [comment]
Hey @Apollon77 , would you please file this feedback on the [GitHub Community Forums](https://github.community/t5/GitHub-Actions/bd-p/actions). This isn't something we can do the in the toolkit.

Our development team monitors that community for new enhancements and general feedback.

**Comment by Apollon77** [comment]
Did, thank you!
