### ISSUE TITLE
tracking: publish packages

### ISSUE THREAD

**Issue by ericsciple** [actions/toolkit#261]
Bump patch version and release all modules

Related PRs:
- https://github.com/actions/toolkit/pull/257
- https://github.com/actions/toolkit/pull/221
- https://github.com/actions/toolkit/pull/263
- https://github.com/actions/toolkit/pull/264
- https://github.com/actions/toolkit/pull/287

**Comment by mies386** [comment]
#261
> GITHUB_TOKEN#github.org
