### ISSUE TITLE
How to SSH into the machine where my Github action is running similar to what we were doing in Travis?

### ISSUE THREAD

**Issue by kumarranjansingh** [actions/toolkit#266]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.  

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#contacting-support)

If your issue is relevant to this repository, please include the information below:

**Describe the enhancement**
A clear and concise description of what the features or enhancement you need.

**Code Snippet**
If applicable, add a code snippet to show the api enhancement.

**Additional information**
Add any other context about the feature here.

**Comment by ericsciple** [comment]
@bryanmacfarlane @chrispat any idea where this is on the backlog?

**Comment by bryanmacfarlane** [comment]
👋 This isn't a toolkit issue - it's a bigger service enhancement in cooperation with compute.  Please open an issue on GitHub community.  We do have a backlog item covering this but it's not in the next quarters planning.
