### ISSUE TITLE
Documentation for Docker LABELs, e.g. "com.github.actions.name"

### ISSUE THREAD

**Issue by edhgoose** [actions/toolkit#281]
**Describe the enhancement**
A number of examples of GitHub actions using Dockerfiles use the following functionality:

```
LABEL "com.github.actions.name"="Markdown Spell Checker"
LABEL "com.github.actions.description"="Markdown Spell Checker"
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="green"
```

For instance, https://tech.paulcz.net/blog/intro-to-github-actions/#step-2-spellcheck, writes the following:

> Note: the LABELs are important to github actions and are documented [here](https://developer.github.com/actions/creating-github-actions/creating-a-docker-container/#label)

Unfortunately, the URL documented doesn't work any more and redirects here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions

Is this because those features are no longer used? If not, please can we have some documentation for them? I couldn't find any references to suggest they were officially deprecated.

**Comment by bryanmacfarlane** [comment]
This doesn't seem to be an issue with the toolkit repo.  You should likely report at github community.  If I'm mistaken and there's a dockerfile in this repo, you're referring to, add it and I'll re-open.

**Comment by edhgoose** [comment]
My apologies @bryanmacfarlane - I wasn't aware of the GitHub Community. I've found someone has asked a similar question here: https://github.community/t5/GitHub-Actions/Documentation-for-Dockerfile-metadata-labels/m-p/32536#M1172

Thanks!
