### ISSUE TITLE
Can't see my debug logs

### ISSUE THREAD

**Issue by darko-dev** [actions/toolkit#284]
**Describe the bug**

I can't see debug info within workflow logs printed with `core.debug()` from my action. I have set both `ACTIONS_RUNNER_DEBUG ` and `ACTIONS_STEP_DEBUG ` secrets to true but still no debug info is printed.

**To Reproduce**

You can check the action code [here](https://github.com/darko-dev/actions-aws-deploy-to-s3)

There is a simple action with just `core.debug()` call [here](https://github.com/darko-dev/simple-action)

**Expected behavior**

Logs displayed in the workflow logs.

Has someone experienced the same behaviour? 
Thanks

**Comment by thboop** [comment]
Hey @darko-dev ! Thanks for the clean examples!

I took a look at `simple-action`. It appears the code to actually execute the run() function is missing. Right now, that action appears to be a no-op

I forked  the action and modified it here: https://github.com/thboop/simple-action/commit/09871fa392a1eebeba766f87352f6822606cfc8f

After doing so I was able to see the expected output:

![image](https://user-images.githubusercontent.com/52323235/71847848-ff544b80-309b-11ea-9c42-6bc1336e81de.png)

I took a look through actions-aws-deploy-to-s3 as well and it seems to be missing `run()` as well


Please let me know if this resolves the issue for you!

**Comment by darko-dev** [comment]
Hi @thboop, yeah, I somehow missed that part. 
Thank you so much for your time, it runs now!
