### ISSUE TITLE
Three unit tests timing out on hosted mac

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/toolkit#286]
● @actions/exec › Exec roots relative tool path using process.cwd

    thrown: "Exceeded timeout of 5000ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      531 |   })
      532 | 
    > 533 |   it('Exec roots relative tool path using process.cwd', async () => {
          |   ^
      534 |     let exitCode: number
      535 |     let command: string
      536 |     if (IS_WINDOWS) {

      at packages/exec/__tests__/exec.test.ts:533:3
      at Object.<anonymous> (packages/exec/__tests__/exec.test.ts:18:1)

**Comment by thboop** [comment]
Doesn't seem to be an issue anymore
