### ISSUE TITLE
"add-matcher" doesn't work from within a Docker container

### ISSUE THREAD

**Issue by TrueBrain** [actions/toolkit#305]
**Describe the bug**
https://github.com/actions/toolkit/issues/56#issuecomment-536753187 suggests that "add-matcher" works from within a Docker container. I couldn't find a way to get this to work. "add-matcher" always uses the host file-system to lookup the file, and can't read a file from the Docker container (that I could find).

**To Reproduce**
See https://github.com/TrueBrain/actions-flake8/blob/initial_work/entrypoint.sh#L5.
Removing the `cp` on line 4 and use `flake8-matcher.json` instead of the full path on line 5. This will result in a "file not found" error.

**Expected behavior**
"add-matcher" to work from within a Docker container.

**Additional context**
Honestly, I can fully understand that "add-matcher" uses the host file-system. So maybe this is not a bug or unexpected.

The main thing that is puzzling me a bit, is that the comment linked suggests it should work. But I couldn't find any example of this, and the documentation doesn't talk about this. So I am not sure. As a result: this ticket, in the hope one of you can shed some light on this topic :)

If the `cp` is the expected solution, I would love to get some pointers what a good folder is to copy this to. Using the workflow folder for this feels a bit ugly.
Or possibly my solution is just completely bananas, and you have a much better solution in mind.

Tnx!

**Comment by ericsciple** [comment]
updated docs too early https://github.com/actions/toolkit/pull/341

fixed bug in runner to make this work... https://github.com/actions/runner/pull/331

after the new runner rolls out (sometime over next couple weeks), will restore docs.

**Comment by TrueBrain** [comment]
Been a while, but I finally got to testing the `$HOME` solution. Works like a charm :) Thank you very much!
