### ISSUE TITLE
[Question] Why use this over execa

### ISSUE THREAD

**Issue by runspired** [actions/toolkit#315]
[execa](https://github.com/sindresorhus/execa) is what is standardly used for cross-platform standardized execution. I'm curious what advantages the [exec](https://github.com/actions/toolkit/tree/master/packages/exec) toolkit package offers us that execa does not already offer. On the surface they seem largely interchangeable.

**Comment by thboop** [comment]
Note: I'm not familiar with the `execa` module

The toolkit is designed to provide everything you need to create actions. There are other node modules which may overlap with some of its functionality, and feel free to use those, but in general we aim to have first party libraries that anyone can use that are specialized for developing actions.
