### ISSUE TITLE
Problem matcher multiline support for message field

### ISSUE THREAD

**Issue by stefanbuck** [actions/toolkit#319]
**Describe the enhancement**

It seems like the current implementation does not support escape sequences like `\n` or `\t` for the message field. I wonder if there is a special reason for that. I want to write a Problem Matcher for [jest](https://jestjs.io/) and this requires multiline support to make the output useful. 

### Current dialog
![image](https://user-images.githubusercontent.com/1393946/72844335-932d3680-3c9c-11ea-9f3d-a8e042b47f72.png)

### Expected dialog

![image](https://user-images.githubusercontent.com/1393946/72844515-f28b4680-3c9c-11ea-92d3-f9fe00553062.png)

**Comment by JasonGross** [comment]
There's some documentation [here](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md#multiline-matching) on how to match multiline error messages by giving separate regexps for each line, and optionally looping the final regexp until no match is found.  Is this sufficient, or do you need more flexibility?

**Comment by stefanbuck** [comment]
The issue describes a limitation on the message field and the way how it is present in the UI. It doesn't support multiple lines which is needed to provide useful jest output to the user.

**Comment by stefanbuck** [comment]
URL encoding `\n` does the trick.

**Comment by mattmurp** [comment]
Thanks, that worked!

**Comment by teohhanhui** [comment]
The workaround by @stefanbuck basically doesn't use problem matchers.

So this is still a desirable feature, to be able to match a *single* error which spans multiple lines of output.

**Comment by smorimoto** [comment]
@teohhanhui You are exactly right. I opened a new issue to follow up on this issue: https://github.com/actions/toolkit/issues/1540
