### ISSUE TITLE
@actions/core 1.2.2 breaks when trying to set a number as output

### ISSUE THREAD

**Issue by dguo** [actions/toolkit#321]
**Describe the bug**

My team has code like:

`core.setOutput("test_db_migrations", testDbMigrations ? 1 : 0);`

This broke with the 1.2.2 release because it expects the output to be a string.

The error is: `TypeError: (s || "").replace is not a function` and occurs at `node_modules/@actions/core/lib/command.js:66:10)`.

**To Reproduce**

Try to set a number as output.

**Expected behavior**

The library could do a `.toString()`, or I recommend at least updating the README to make it clear that the output value has to be a string.

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by wpscholar** [comment]
What if I want to return an object?

**Comment by gr2m** [comment]
`setOutput` does not support objects. You can set it to a stringified object, but then have to parse it later

**Comment by thboop** [comment]
Resolved in #405
