### ISSUE TITLE
Octokit deprecation warning

### ISSUE THREAD

**Issue by JasonEtco** [actions/toolkit#333]
**Describe the bug**

Hey folks 👋 I'm seeing a deprecation warning for `@octokit/rest.js` when importing `@actions/github`. This looks to be the offending code (h/t @joshmgross):

https://github.com/actions/toolkit/blob/432a78c48c941e90eedf7911ff0aa271bacad97b/packages/github/src/github.ts#L12

And the warning:

```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```

Looks like perfectly valid warning! cc-ing @gr2m for 👀 

**Additional context**

`@actions/github`: `2.1.0`
`@octokit/rest`: `16.43.1`

**Comment by joshmgross** [comment]
Should be fixed now with https://github.com/actions/toolkit/pull/332
