### ISSUE TITLE
core: do not trim spaces on value returned by getInput

### ISSUE THREAD

**Issue by myitcv** [actions/toolkit#339]
**Describe the bug**

As I raised over in [the community forums](https://github.community/t5/GitHub-Actions/Unclear-why-actions-core-trims-value-returned-by-getInput/m-p/45537/highlight/true#M6252), the [core package](https://github.com/actions/toolkit/tree/master/packages/core) trims the value returned by getInput:

https://github.com/actions/toolkit/blob/432a78c48c941e90eedf7911ff0aa271bacad97b/packages/core/src/core.ts#L74

I might well be missing something here, but I consider this a bug because it precludes leading/trailing spaces from ever being significant in input values. If the the caller of `getInput` wants to trim space on the value returned, they can make that decision. As things stand, leading/trailing spaces can never be significant in input values.

This puts input values at odds with environment variables on Linux and macOS (at least).

Please can someone provide the motivation behind this decision? 

Thanks

**To Reproduce**

n/a

**Expected behavior**

Per above description. 

**Screenshots**

n/a

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

None

**Comment by bryanmacfarlane** [comment]
I agree.

**Comment by iamalisajid** [comment]
+1
