### ISSUE TITLE
@actions/exec vs child_process.exec

### ISSUE THREAD

**Issue by jjangga0214** [actions/toolkit#345]
How are they different?

Is there a special reason to use `@actions/exec` over node's `child_process.exec`?

Thanks.

**Comment by Kerizer** [comment]
Looks like pipes not working if command is executed with `@actions/exec`, so they are different.
Not sure if this is by design

**Comment by thboop** [comment]
@jjangga0214 , `@actions/exec` handles additional items like escaping for you, and is designed to be easier to use than child_process.

**Comment by jjangga0214** [comment]
@thboop Thanks for the answer. 

As @Kerizer mentioned, `pipeline` doesn't work. `&&` doesn't, either. Is this by intentional design?

> additional items like escaping for you

What kind of escaping, in detail?

Thanks
