### ISSUE TITLE
Document tool cache details

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/toolkit#363]
Open source the doc which details how the tool cache works.

**Comment by eine** [comment]
Ref eine/setup-msys2#23

**Comment by thboop** [comment]
This should be covered by https://docs.github.com/en/enterprise-server@2.22/admin/github-actions/managing-access-to-actions-from-githubcom/setting-up-the-tool-cache-on-self-hosted-runners-without-internet-access
