### ISSUE TITLE
URLs for artifacts

### ISSUE THREAD

**Issue by krzkaczor** [actions/toolkit#364]
Hey!

With `@actions/artifact` it's possible to upload/download artifacts. Artifact can be a HTML report generated by some kind of tool. 

Is it possible to obtain a URL to uploaded artifact so it's possible to browse it in browser? (and later post it back to GH interface). 

Are such URLs public even for private projects?

**Comment by thboop** [comment]
Hey @krzkaczor , I want to to make sure I'm understanding this enhancement correctly. 

Are you are looking for a way to upload an artifact in a private repo and then get a public URL for that artifact? If there isn't a specific toolkit function you want here, we should transfer this issue to `actions/upload-artifact`, they will be able to assist you more!

I think they have a related issue here https://github.com/actions/upload-artifact/issues/14

**Comment by krzkaczor** [comment]
Thanks! That's helpful.
