### ISSUE TITLE
@actions/github should populate Run Number and Run ID

### ISSUE THREAD

**Issue by joshmgross** [actions/toolkit#371]
### Background
The `@actions/github` package populates a GitHub `Context` similar to [`github` context](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) available in workflows, see https://github.com/actions/toolkit/blob/master/packages/github/src/context.ts

### Issue
This context is missing the Run ID and Run Number, available as `GITHUB_RUN_NUMBER` and `GITHUB_RUN_ID`, see https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

We should add these values to the package's context and ensure that the workflow `github` context matches what's available in this package.

Related: https://github.com/actions/toolkit/issues/65

**Comment by gitwdel** [comment]
#371
