### ISSUE TITLE
TypeError: (s || "").replace is not a function

### ISSUE THREAD

**Issue by bnb** [actions/toolkit#398]
**Describe the bug**
When trying to run an action, I am getting the following error from `@actions/core`:

```
(node:2588) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:60:35)
    at issueCommand (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:23:30)
    at Object.issue (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:27:5)
    at error (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/core.js:127:15)
    at Object.setFailed (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/core.js:101:5)
    at action (/home/runner/work/_actions/cutenode/action-meeting/dev/index.js:62:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Last commit where it works:
- https://github.com/cutenode/action-meeting/commit/f88068b6ec7c79c60712f1ec7cedf71d13aaada4

It stops working in this commit:
- https://github.com/cutenode/action-meeting/commit/71fa544290caaf49e3d17626208b5b9c2a3875dc

**EDIT:** Updated to only reflect the commit it stopped working in. This was triggered by passing an incorrect type to Octokit.js for the `labels` property - I was passing a string and it required an array. Since the project was erroring because of that and the error being passed was not a string, I was encountering this issue.

**Expected behavior**
For `@actions/core` to handle errors more effectively.

**Comment by bnb** [comment]
For reference, this is the method that's failing:

https://github.com/actions/toolkit/blob/master/packages/core/src/command.ts#L76

**Comment by bnb** [comment]
Here is the last working run (https://github.com/cutenode/action-meeting/commit/f88068b6ec7c79c60712f1ec7cedf71d13aaada4): 
- https://github.com/bnb/meet/runs/546925718?check_suite_focus=true

Here is the run that includes the change (https://github.com/cutenode/action-meeting/commit/14879a2cf7abd75ee9f2c5302c22f0a3997c0994 or https://github.com/cutenode/action-meeting/commit/71fa544290caaf49e3d17626208b5b9c2a3875dc) that triggered this:
- https://github.com/bnb/meet/actions/runs/66883811

**Comment by gomorizsolt** [comment]
As of right now, the object has to be stringified. There's an on-going feature request(#386) to support error objects as well.

**Comment by bnb** [comment]
Thanks for that, it solved my problem. There is zero reason that should be limited to a string, and as far as I can tell it's not documented anywhere other than the code itself... which is not documentation.

FWIW, here's a helper function for anyone that encounters this and is lazy:

```
const core = require('@actions/core')

function catchError (error) {
  const passErrorAsAStringBecauseItsRequired = error.toString()
  process.exitCode = 1
  core.setFailed(passErrorAsAStringBecauseItsRequired)
}

module.exports = catchError
```

Just require this in your `catch` blocks and you should be good to go.

**Comment by gomorizsolt** [comment]
Doesn't [`core.setFailed()`](https://github.com/actions/toolkit/tree/master/packages/core#exit-codes) already sets the status code?

> setFailed logs the message and sets a failing exit code

According to the docs, it's supposed to do so.

**Comment by bnb** [comment]
May have been me overcompensating for the errors I was having. I encountered several cases in trying to debug this for 5 hours where the action successfully passed but the code errored out since unhandled promise rejections were not fully erroring the process.

Updated.
