### ISSUE TITLE
Steps context not filled by default.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [actions/toolkit#415]
https://github.com/actions/toolkit/issues/338#issuecomment-614302167

**Comment by afwn90cj93201nixr2e1re** [comment]
@ericsciple @

**Comment by thboop** [comment]
Hey @afwn90cj93201nixr2e1re , I responded to your comment here: https://github.com/actions/toolkit/issues/338#issuecomment-620798931

Let me know if that does not resolve your issue and we can reopen this ticket!

**Comment by afwn90cj93201nixr2e1re** [comment]
It's fine, thx.
