### ISSUE TITLE
Cannot set deployment state to in_progress

### ISSUE THREAD

**Issue by sergeysova** [actions/toolkit#443]
**Describe the bug**

**To Reproduce**
1.
```js
    client.repos.createDeploymentStatus({
      ...context.repo,
      deployment_id: deploymentId,
      state: "in_progress",
    });
```
2. `HttpError: Validation Failed`
3. Because: https://developer.github.com/v3/repos/deployments/#parameters-2

> To use the inactive state, you must provide the application/vnd.github.ant-man-preview+json custom media type. To use the in_progress and queued states, you must provide the application/vnd.github.flash-preview+json custom media type.

**Expected behavior**
`createDeploymentStatus` automatically sets media type if `state` is requires it.

Ref: https://github.com/authmenow/releases/runs/630056476?check_suite_focus=true (Deployment success), https://github.com/chrnorm/deployment-status/issues/8

**Comment by thboop** [comment]
This should be fixed in `@actions/github 5.0.0` please let me know if you are still seeing issue and we can reopen the issue
