### ISSUE TITLE
Requirement for token when using github api for custom actions.

### ISSUE THREAD

**Issue by Tylertron1998** [actions/toolkit#445]
**Describe the enhancement**
The current requirement for a token to use annotations is a little strange. I'm currently building a custom action and asking users to give me a token so I can put annotations on pull requests based on the action result is something I'd rather not do - to anyone with a little less understanding, this could seem a little nefarious. 

What I'd like to see is a way to be able to post annotations for the current action run in the context it's run in - i.e. if a pull request triggers my-cool-action@v1 then my-cool-action@v1 should be able to add annotations for that pull request **and only** that pull request.

**Additional information**
For some strange reason, I can see that running `dotnet build` gives annotations - which is confusing as dotnet build certainly does not integrate with github, and even more confusingly doesn't seem to require an api key.

**Comment by thboop** [comment]
Hey @Tylertron1998 , I'd like to understand your use case a little better. I've tried to outline the options available to you below!

> For some strange reason, I can see that running dotnet build gives annotations

This is likely being done via [Problem Matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md). Do you run a setup-action like [setup-dotnet](https://github.com/actions/setup-dotnet) that registers a problem matcher automatically?

You shouldn't need `@actions/github` to create annotations. We also support the following, which do not require a token.

- If you are trying to create annotations from structured output (such as compile output), you can register a problem matcher, as outlined in the documentation above.
- You may also choose to create annotations via the `error` and `warning` functions in `@actions/core`.

We also have an open issue to see how we can improve this experience outside of the `warning` and `error` functions: https://github.com/actions/toolkit/issues/186

**Comment by Tylertron1998** [comment]
Interesting - I had no idea about problem matchers! I'll check them out!

**Comment by thboop** [comment]
I'm going to close this ticket for now, but if you have any more questions or feedback after checking it out please let me know!
