### ISSUE TITLE
[BUG] ##[error]Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by rodrigondec** [actions/toolkit#465]
**Describe the bug**
I reported this bug on the action I'm using: alex-page/github-project-automation-plus#39.
> read this issue to have better understanding of the discussions we had.

I'm receiving the error `##[error]Parameter token or opts.auth is required` on [this run](https://github.com/idvogados/idvogados.github.io/pull/16/checks?check_run_id=668944788) on my CI

> I found this issue actions/toolkit#324 by googling the error returned.

On [this line of code of the action I'm using](https://github.com/alex-page/github-project-automation-plus/blob/b4737e8091f494be6ec5afdb07dc388a13e5bd6d/src/index.js#L18) is used:

```js
const octokit = new github.GitHub(token);
```

In the package `@actions/github` on [this line of code](https://github.com/actions/toolkit/blob/0471ed4ad777277385d971c0c86c87917e9373df/packages/github/src/github.ts#L39) (which probably raises the error) is used:
```js
constructor(token: string, opts?: Omit<Octokit.Options, 'auth'>)
  constructor(opts: Octokit.Options)
  constructor(token: string | Octokit.Options, opts?: Octokit.Options) {
    super(GitHub.getOctokitOptions(GitHub.disambiguate(token, opts)))

    this.graphql = GitHub.getGraphQL(GitHub.disambiguate(token, opts))
  }
```
> Github extends Ocktokit. So is super = Ocktokit

In the package `@ocktokit/core` on [this line of code](https://github.com/octokit/core.js/blob/f099459fd01be79187275ddf47d77a2797188c6a/src/index.ts#L132) there's the following explanation/documentation:
```js
constructor(options: OctokitOptions = {}) {
[...]

// (1) If neither `options.authStrategy` nor `options.auth` are set, the `octokit` instance
    //     is unauthenticated. The `this.auth()` method is a no-op and no request hook is registred.
    // (2) If only `options.auth` is set, use the default token authentication strategy.
    // (3) If `options.authStrategy` is set then use it and pass in `options.auth`. Always pass own request as many strategies accept a custom request instance.
    // TODO: type `options.auth` based on `options.authStrategy`.
```

**To Reproduce**
1. Go to [this run](https://github.com/idvogados/idvogados.github.io/pull/16/checks?check_run_id=668944788) 
2. Click on 're-run all jobs'
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3301060/81755574-858bfe80-948f-11ea-831b-3de3218eec20.png)
![image](https://user-images.githubusercontent.com/3301060/81755592-92105700-948f-11ea-909b-5b0af074a577.png)

**Additional context**
Should be passed others args besides the token on this line from the action?
```js
const octokit = new github.GitHub(token);
```

The construct does accept other options:
```js
constructor(token: string, opts?: Omit<Octokit.Options, 'auth'>)
```

On the [official documentation of `@actions/github`](https://github.com/actions/toolkit/tree/master/packages/github#usage) is used only `token` on the constructor.

Did we miss some official documentation? Should issue be opened on [`@ocktokit/core`](https://github.com/octokit/core.js)?

**Comment by thboop** [comment]
Hey @rodrigondec,

I think you are encountering a different issue here. For security, [Secrets are not currently available to forks](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow).

[This call](https://github.com/alex-page/github-project-automation-plus/blob/b4737e8091f494be6ec5afdb07dc388a13e5bd6d/src/index.js#L10) to `getInput` is likely returning the empty string.

`const octokit = new github.GitHub("")`, will return that error message.

The [forked repo](https://github.com/mastercoks/idvogados.github.io) likely does not have this secret set.

We are currently evaluating features to enable [secrets in forks](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/td-p/30678)

**Comment by rodrigondec** [comment]
> Hey @rodrigondec,
> 
> I think you are encountering a different issue here. For security, [Secrets are not currently available to forks](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow).
> 
> [This call](https://github.com/alex-page/github-project-automation-plus/blob/b4737e8091f494be6ec5afdb07dc388a13e5bd6d/src/index.js#L10) to `getInput` is likely returning the empty string.
> 
> `const octokit = new github.GitHub("")`, will return that error message.
> 
> The [forked repo](https://github.com/mastercoks/idvogados.github.io) likely does not have this secret set.
> 
> We are currently evaluating features to enable [secrets in forks](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/td-p/30678)

It makes sense. Ty for the response.

**Comment by homomorfism** [comment]
test 123
