### ISSUE TITLE
Problem matchers: Code is not actually using EcmaScript-style regexs as documented

### ISSUE THREAD

**Issue by lumaxis** [actions/toolkit#482]
I'm not 100% sure that this is really the case since my understanding of Dotnet and C# is pretty limited but the [current documentation](https://github.com/actions/toolkit/blob/30e0a77337213de5d4e158b05d1019c6615f69fd/docs/problem-matchers.md#regular-expression-not-matching) seems to suggest that the problem matchers use EcmaScript-style regex syntax but I don't see the [necessary options](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions?view=netcore-3.1#fields) being passed here: https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Runner.Worker/IssueMatcher.cs#L68
The default seems to be to use canonical regex synatx: https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options#default-options

**Comment by thboop** [comment]
Hey @lumaxis , they are passed in here: https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Runner.Worker/IssueMatcher.cs#L408

I'm going to close this issue out, as it appears to be working as expected, but if you are still seeing issues with it not using EMCAScript let me know and I'll reopen!

**Comment by lumaxis** [comment]
Fantastic, thanks for digging that up!
