### ISSUE TITLE
Random error on Mac OS: [error]Too Many Requests

### ISSUE THREAD

**Issue by evandrocoan** [actions/toolkit#503]
Moving from https://github.com/actions/cache/issues/267#issuecomment-646383662

> I just this new kind of random error which randomly breaks the build only for Mac OS: https://github.com/ankitects/anki/pull/604/checks?check_run_id=786490395#step:26:10
> ```
> Run actions/upload-artifact@v1
> Uploading artifact 'anki_macos_python3.7' from '/Users/runner/runners/2.263.0/work/anki/anki/dist' for run #2272
> Uploading 3 files
> Unable to copy file to server StatusCode=TooManyRequests: Too Many Requests. Source file path: /Users/runner/runners/2.263.0/work/anki/anki/dist/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl. Target server path: anki_macos_python3.7/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl
> Cannot continue uploading files, so draining upload queue of 1 items.
> Fail to upload '/Users/runner/runners/2.263.0/work/anki/anki/dist/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl' due to 'Critical failure uploading '/Users/runner/runners/2.263.0/work/anki/anki/dist/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl''.
> GitHub.Runner.Plugins.Artifact.UploadFailedException: Critical failure uploading '/Users/runner/runners/2.263.0/work/anki/anki/dist/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl'
>    at GitHub.Runner.Plugins.Artifact.FileContainerServer.UploadAsync(RunnerActionPluginExecutionContext context, Int32 uploaderId, CancellationToken token)
> File error 'Critical failure uploading '/Users/runner/runners/2.263.0/work/anki/anki/dist/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl'' when uploading file '/Users/runner/runners/2.263.0/work/anki/anki/dist/ankirspy-2.1.28+40eab4bd-cp37-cp37m-macosx_10_7_x86_64.whl'.
> ##[error]Too Many Requests
> ##[error]Exit code 1 returned from process: file name '/Users/runner/runners/2.263.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
> ```

**Comment by konradpabjan** [comment]
Please switch over to the `v2` version of `upload-artifact` and `download-artifact`. 

The `@actions/artifact` package that you see in: https://github.com/actions/toolkit/tree/main/packages/artifact is all typescript based while the `v1` are effectively C# plugins that are tied to the runner. No new fixes or improvements are being made to the v1 versions of the actions. There is a good chance that the bug you hit has already been fixed.

If you still hit issues while using the `v2` version of `upload-artifact` please open an issue in [upload-artifact](https://github.com/actions/upload-artifact)
