### ISSUE TITLE
Unable to restore cache to certain locations

### ISSUE THREAD

**Issue by FranciscoPombal** [actions/toolkit#506]
**Describe the bug**

This action seems to unable to restore cache to certain locations. In this case, that would be paths starting with `C:\` on Windows runners.

Note: I'm using https://github.com/lukka/run-vcpkg which uses the `@actions/cache`.

**To Reproduce**

1. Try to setup caching to/from a directory under `C:\...` on Windows runners
2. Verify that one run finishes successfully and saves the cache
3. Start another run that would be able to restore from the previously saved cache
4. Restoring cache fails with these errors:

> ```
> C:/qbt_tools/vcpkg/: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg'
> C:/qbt_tools/vcpkg/.artifactignore: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.artifactignore'
> C:/qbt_tools/vcpkg/.git/: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.git'
> C:/qbt_tools/vcpkg/.gitattributes: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.gitattributes'
> C:/qbt_tools/vcpkg/.github/: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.github'
> C:/qbt_tools/vcpkg/.gitignore: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.gitignore'
> C:/qbt_tools/vcpkg/.vcpkg-root: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.vcpkg-root'
> C:/qbt_tools/vcpkg/bootstrap-vcpkg.bat: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\bootstrap-vcpkg.bat'
> C:/qbt_tools/vcpkg/bootstrap-vcpkg.sh: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\bootstrap-vcpkg.sh'
> ...
> ... (same for all other vcpkg files)
> ...
> tar.exe: Error exit delayed from previous errors.
> restoreCache() failed: 'Error: Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1'.
> Cache miss.
> ```

**Expected behavior**

Cache restoration succeeds.

**Desktop (please complete the following information):**

Windows Server 2019 runners

**Additional context**

_More context can be found in the original report at https://github.com/lukka/run-vcpkg/issues/25_

**Comment by FranciscoPombal** [comment]
https://github.com/lukka/run-vcpkg/issues/25#issuecomment-649888650

> Good news: looks like the issue can be worked around simply by creating the path prefix in advance. So, for example, if using `vcpkgDirectory: C:\qbt_tools\vcpkg` in the vcpkg setup step, one would need to run something like `mkdir C:\qbt_tools` before the vcpkg setup step.
> 
> Make of this what you will, I'm not sure if the underlying problem resides in your action or in the upstream `cache` action.
> 
> Here is an example run where this workaround was used to get cache restoration working: https://github.com/FranciscoPombal/qBittorrent/actions/runs/148077320.

**Comment by NPC99** [comment]
#380

**Comment by FranciscoPombal** [comment]
Looks like the issue is indeed fully resolved by https://github.com/lukka/run-vcpkg/pull/26, sorry for the inconvenience.
