### ISSUE TITLE
Running on the wrong commit

### ISSUE THREAD

**Issue by facundobatista** [actions/toolkit#525]
It runs the action on the project's wrong commit

Steps:

- go to https://github.com/PyAr/CDPedia/pull/274
- scroll down to the list of commits
- see there's one with message "Flake 8 issues": hash 5d8abdc 
- click on the X at the hash's left, should open the "some checks were not successful" pop
- click on the "Details" of the 3.7 run, should go to https://github.com/PyAr/CDPedia/runs/880106851
- in the "logs" pane, expand the "run actions/checkout@v2" group
- in there, see the following:

```
 commit 5e52271eb4cfdbe501fb96f715efaf10b88d176c
Author: marian-vignau <mavignau@gmail.com>
Date:   Fri Jul 17 00:38:32 2020 +0000

    Merge 2b611cc85e9500c0d94f1e01eaf0bcaf057d7119 into 7d813b430b1b41968577387df75c7ba98814ea65
```

That doesn't match with the `5d8abdc` we were seeing in the PR's page!

Thanks,

**Comment by thboop** [comment]
Hey @facundobatista , thanks for filing this issue. We are aware of it happening very infrequently, and are tracking in the `actions/checkout` repo.

https://github.com/actions/checkout/issues/237

I'm going to close this out for now. fyi @ericsciple

**Comment by marian-vignau** [comment]
It happens VERY frequently. 
See the same kind of error in https://github.com/PyAr/CDPedia/runs/871872757
In this run, attached to the commit  ed80113, in the log is mentioned this commit a4f842e8cd3b925513004b2adf64b626c3faa6cc, on the "Run actions/checkout@v2" section.
