### ISSUE TITLE
Support multiple compression algorithms when restoring cache

### ISSUE THREAD

**Issue by Vampire** [actions/toolkit#543]
Currently if you create a cache entry on a system where `gzip` is used and then restore the cache on a system where `zstd` is used, you get a cache miss.
It would be nice if instead mutliple compression algorithms were supported.
Something like this:

on cache creation:
- `zstd` with `--long` present
  - use `zstd` with `--long`
  - end
- `zstd` present
  - use `zstd`
  - end
- use `gzip`

on cache restoring:
- `zstd` with `--long` present
  - if according cache entry is present
    - use that
    - end
  - if according cache entry is **not** present
    - continue
- `zstd` present
  - if according cache entry is present
    - use that
    - end
  - if according cache entry is **not** present
    - continue
- use `gzip`
  - if according cache entry is present
    - use that
    - end

This way, for example a cache entry created on a `gzip` system can be used even on a `zstd` system.

And to be even fancier, when restoring a "lower" level (`gzip` or `zstd` on `zstd` with `--long`, or `gzip` on `zstd`), the file could be recompressed with the "higher" level and a new cache entry for that higher level created, so that next time it can be used more efficiently.

**Comment by pdotl** [comment]
Hi @Vampire , while we do multiple compression algorithms, they are not interchangeable. AFAIK, tar created using `zstd` can only be decompressed using `zstd` and vice-versa. The idea of having the customer choose their own algo does have merit and can be looked into. For now, closing this issue as this feature is not planned currently. Feel free to provide feedback on [#984](https://github.com/actions/cache/issues/984) for the current proposal on changes to tar compression.

**Comment by Vampire** [comment]
@pdotl I nowhere suggested to let the customer choose the algorithm.
It was an algorithm that should automatically work, so that for example a build on `windows-2016` could be used on `windows-2019` and newer. (I'm aware that 2016 is not there anymore, but that was the original problem that made me write this suggestion)

**Comment by pdotl** [comment]
@Vampire apologies for the misunderstanding. We have now proposed defaulting to the same tar and compression algorithm wherever possible to ensure cross-os compatibility. Also we have ensured to default to the tools available across all hosted runners so this should not be a problem anymore. Feel free to drop by [#984](https://github.com/actions/cache/issues/984) to provide feedback. Many thanks!

**Comment by Vampire** [comment]
Yeah, sure, if all use the same (also in the future) this is of course obsolete :-)

**Comment by Phantsure** [comment]
@Vampire We have released a new beta release which should fix this issue. Try tag: `actions/cache@3.1.0-beta`. Head over to discussion for feedback: https://github.com/actions/cache/discussions/1019

**Comment by Vampire** [comment]
> Yeah, sure, if all use the same (also in the future) this is of course obsolete :-)

Well, the "also in the future" does not hold.
Currently the same problem happens again with the new windows-11-arm runners where no zstd is available.
You can neither create a cache on those and restore it on other images nor the other way around currently as also the compression algorithm selection request was rejected back then. :-(
