### ISSUE TITLE
Add docs for ##[] commands from scripts

### ISSUE THREAD

**Issue by damccorm** [actions/toolkit#57]
e.g. `##[error]Error message`

**Comment by bryanmacfarlane** [comment]
This is changing to ::

**Comment by warrenbuckley** [comment]
Yes curious to know what this @damccorm as saw a few commits/lines in other actions such as actions/setup-node etc...

**Comment by bryanmacfarlane** [comment]
We will document.  The ## was problematic as that's a comment in bash so it require quoting which was inconsistent across platforms.  The latest version of the runner has the changes so it's now ::.  Now that it has rolled out, we will doc for scripts and the toolkit will react.

**Comment by 1138-4EB** [comment]
I am currently using the following bash function to wrap commands in groups:

``` bash
pgroup () {
  printf '##[group]'
    echo "$@"
    "$@"
  echo '##[endgroup]'
}
```

Although @bryanmacfarlane commented that it changed 3 days ago, it is still working. Will these break? Or is it independent from this issue?

**Comment by bryanmacfarlane** [comment]
We will support ## for a few months and advise / sunset.  The new syntax is the same but uses `::` instead of `##`.  It's supposed to be rolling to rings any day now (and might be in yours as I write this).

**Comment by damccorm** [comment]
Added docs in #105 if anyone is still looking for guidance/wants to take a look
