### ISSUE TITLE
Update add-path command

### ISSUE THREAD

**Issue by renanmav** [actions/toolkit#601]
**Describe the bug**

GitHub updated how we add env vars to PATH, you can read more about it here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

This repository is used by many custom actions and we are getting warnings about the deprecation above.

I believe the problem is happening on this line:
https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L58

**To Reproduce**
1. Use this action https://github.com/ReactiveCircus/android-emulator-runner in a repository
2. Check the run and see a warning being shown to you

**Expected behavior**

It should not create a warning when adding env vars to PATH.

**Screenshots**

![Captura de Tela 2020-10-07 às 17 09 53](https://user-images.githubusercontent.com/43140758/95382376-ee04cd80-08bf-11eb-9da7-b624e273a9aa.png)

This happened with me because I’m using this action that depends on this repository.

- https://github.com/ReactiveCircus/android-emulator-runner/blob/8feb8a564ade127617f5cc53b515fd5ea05013e3/lib/sdk-installer.js#L58
- https://github.com/ReactiveCircus/android-emulator-runner/blob/8feb8a564ade127617f5cc53b515fd5ea05013e3/lib/sdk-installer.js#L32

**Desktop:**
 - OS: macOS
 - Browser Chrome

**Comment by derek-burdick** [comment]
Please not that 'set-env' is also deprecated and should be corrected.

**Comment by peaceiris** [comment]
> I believe the problem is happening on this line:
>
> https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L58

Your URL is pointing to the `master` branch. Those (`add-path` and `set-env`) are already fixed at the latest branch `main` in [1.2.6](https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/RELEASES.md).

[https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts](https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/src/core.ts)

**Comment by thboop** [comment]
> > I believe the problem is happening on this line:
> > https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L58
> 
> Your URL is pointing to the `master` branch. Those (`add-path` and `set-env`) are already fixed at the latest branch `main` in [`1.2.6`](https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/RELEASES.md). Just update `@actions/core`.
> 
> [https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts](https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/src/core.ts)

This is correct, I'm going to close this issue, but if you encounter issues after updating `@actions/core`, and checking in those updates, please let me know and I'll reopen this so we can investigate.
