### ISSUE TITLE
[cache] Uncaught Exception raised in `uploadFile`

### ISSUE THREAD

**Issue by Swatinem** [actions/toolkit#612]
**Describe the bug**

The `uploadFile` / `uploadChunk` code throws inside of a node stream callback (`.on('error')`), which is not propagated properly through the async functions and leads to failures even though all cache calls are wrapped in try/catch.

https://github.com/actions/toolkit/blob/f1b118b2a9f2e4ab5413c9f98ff03cb77f259c2b/packages/cache/src/internal/cacheHttpClient.ts#L254-L258

**To Reproduce**

Not quite sure, I think there was something wrong with the infrastructure or whatever. I got these failures on both Windows and macOS:

https://github.com/getsentry/sentry-rust/runs/1283097472
```
Warning:  uploadChunk (start: 234881024, end: 268435455) failed: write EPIPE
/Users/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:339
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/Users/runner/work/_actions/Swatinem/rust-cache/v1/dist/save/index.js:339:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Expected behavior**
There should be no unhandled exception being raised outside the promise chain.

**Comment by pimeys** [comment]
We get this quite often in our test runs. We have quite a many jobs, and often a few of them just fail due to `bad file descriptor` error.

**Comment by dhadka** [comment]
Fixed in https://github.com/actions/cache/pull/596.  Please let me know if you continue to see this issue.

**Comment by Swatinem** [comment]
All you do in actions/cache#596 is to catch and log the unhandled promise rejection.

I do the same already here: https://github.com/Swatinem/rust-cache/blob/842ef286fff290e445b90b4002cc9807c3669641/src/common.ts#L11

This issue should be about not throwing outside of the promise chain in the first place.
