### ISSUE TITLE
[Documentation issue] core.addPath is deprecated?

### ISSUE THREAD

**Issue by conao3** [actions/toolkit#622]
**Describe the bug**
`core.addPath` seems deprecated. How rewrite our code?

**To Reproduce**
1. The user uses `core.addPath({{path}})`
2. Generates warning such as
```
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
(actual output, [conao3/setup-cask#actions](https://github.com/conao3/leaf-convert.el/runs/1239712968#step:5:102))

**Expected behavior**
Please write suggestion on [core#path-manipulateion](https://github.com/actions/toolkit/tree/main/packages/core#path-manipulation) section

**Screenshots**
None

**Additional context**
None

**Comment by Cyberbeni** [comment]
If you open the link in the warning message it tells you what to do: `Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.`

**Comment by Cyberbeni** [comment]
Your yarn.lock file has the correct version, you need to run `npm run build` and `npm run release` to update the code that will run in a github workflow using your action. (You will also probably need to make a new release on github too)

**Comment by SamuelJohnsonMedia** [comment]
But @actions/core hasnt been updated beyond [1.1.0 which was released in Sept 2019](https://github.com/actions/toolkit/releases)??

**Comment by Cyberbeni** [comment]
https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md

**Comment by thboop** [comment]
Please update to `@actions/core v1.2.6` and let me know if you still see this issue. If so, we can reopen this issue!

You can see on npm the latest version is 1.2.6 https://www.npmjs.com/package/@actions/core

**Comment by conao3** [comment]
All I had to do was an update! I'm new to Node and the local package updates didn't seem to be well reflected in js in `dist` directory.
Now everything good, thanks for the help!
