### ISSUE TITLE
glob: Pattern with trailing `/` unexpectedly matches a file.

### ISSUE THREAD

**Issue by dbartol** [actions/toolkit#628]
**Describe the bug**
When `implicitDescendants` is `true` (the default), a pattern with a trailing slash will match a file path, rather than just a directory path as intended. For example, the pattern `foo/` will match a file named `foo`, rather than just a directory named `foo`. This behavior is inconsistent with other common glob implementations, include `.gitignore` and `node-glob`. It also means that there is no way to specify a pattern that matches only files.

**To Reproduce**
Run the following TypeScript code:
```ts
import * as glob from '@actions/glob';
import * as fs from 'fs';

async function repro(): Promise<void> {
  const globber = await glob.create('foo/', {
    implicitDescendants: true
  });

  await fs.promises.writeFile('foo', 'text');

  const matches = await globber.glob();
  console.log(matches);
}

repro();
```

**Expected behavior**
No matches are found by the globber.

**Actual behavior**
Output (when run from `C:\Src\Repro`):
```
::debug::implicitDescendants 'true'
::debug::followSymbolicLinks 'true'
::debug::implicitDescendants 'true'
::debug::omitBrokenSymbolicLinks 'true'
::debug::Search path 'C:\Src\Repro\foo'
[ 'C:\\Src\\Repro\\foo' ]
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A

**Comment by luketomlinson** [comment]
Resolved by #805
