### ISSUE TITLE
core.addPath is deprecated? 

### ISSUE THREAD

**Issue by actboy168** [actions/toolkit#630]
**Describe the bug**
I updated @actions/core in my action to 1.2.6. Then core.addPath does not seem to work correctly, how should I rewrite my code?

**To Reproduce**
https://github.com/actboy168/setup-luamake

**Comment by peaceiris** [comment]
Duplicate of #622

**Comment by actboy168** [comment]
@peaceiris  I think this is different from #622. I have updated `@actions/core` to the latest, then `core.addPath` failed.

**Comment by peaceiris** [comment]
https://github.com/actboy168/setup-luamake/blob/2ee6b2f519c884b8c6f71703a91d1ab89b78d234/package.json#L22

Please follow the npm basic usage first.

```diff
+    "dependencies": {
+        "@actions/core": "^1.2.6",
+        "@actions/exec": "^1.0.4"
    },
    "devDependencies": {
-        "@actions/core": "^1.2.6",
-        "@actions/exec": "^1.0.4",
        "@zeit/ncc": "^0.20.5"
    }
```

**Comment by actboy168** [comment]
@peaceiris I have changed as you said, but the result is no different.

**Comment by surfraz** [comment]
Hello, I have also tried this with "@actions/core": "^1.2.6", this version is still using the old set-env deprecated method, however the latest commit seems to have the fix to use filecommands. The deprecation warning specifies using 1.2.6: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Please could we have a new version of actions/core created with the fix included

**Comment by peaceiris** [comment]
That's odd. I think the release 1.2.6 already has both the new approach and the old one.

https://github.com/actions/toolkit/blob/e7eb2c741847a05686a1b8df93dea4b244640b17/packages/core/src/core.ts#L67-L75

Actually, [peaceiris/actions-hugo](https://github.com/peaceiris/actions-hugo)@v2.4.13 works well with no errors.

- `peaceiris/actions-hugo@v2.4.12` using `@actions/core 1.2.5` returns the warning about `add-path`
- `peaceiris/actions-hugo@v2.4.13` using `@actions/core 1.2.6` returns no warning

<img width="689" alt="Screen Shot 2020-11-12 at 23 18 11" src="https://user-images.githubusercontent.com/30958501/98951447-9a7c4400-253d-11eb-9626-524c511243d7.png">
<img width="786" alt="Screen Shot 2020-11-12 at 23 18 37" src="https://user-images.githubusercontent.com/30958501/98951460-9e0fcb00-253d-11eb-984c-2d36a69c657f.png">

**Comment by thboop** [comment]
Updating to the v1.2.6 version of `@actions/core` should be the only thing you need to do to resolve this issue.

@surfraz could you please provide a link to the workflow run and action that is failing? Creating a new action and running the core.addPath command I've been unable to reproduce the issue you are running into.

@actboy168
I haven't been able to successfully run the https://github.com/actboy168/setup-luamake action on hosted runners. Is it intended for a self hosted scenario only? Are you able to provide a link to the failing workflow run where `add-path` is not working? Ideally,  with logging showing what you are trying to add to the path.

**Comment by jwtracy** [comment]
It looks like some of the packages still need this version bumped! Namely,

* [packages/glob/package.json](https://github.com/actions/toolkit/blob/main/packages/glob/package.json#L40)
* [packages/tool-cache/package.json](https://github.com/actions/toolkit/blob/main/packages/tool-cache/package.json#L39)
* [packages/artifact/package.json](https://github.com/actions/toolkit/blob/main/packages/artifact/package.json#L40)

**Comment by actboy168** [comment]
@thboop It should not need a special host.
https://github.com/actboy168/setup-luamake/blob/master/.github/workflows/test.yml

**Comment by thboop** [comment]
@jwtracy I've gone ahead and bumped those packages with new versions of `@actions/core`
```
@actions/glob 0.1.1
@actions/tool-cache 1.6.1
@actions/artifact 0.4.1
```

However, they weren't using the `addPath` or `exportVariable` functions, so they were not vulnerable.


@actboy168 , do you have a link to a run where you see the error annotation about add-path not working correctly?

I looked at https://github.com/actboy168/setup-luamake/actions/runs/360842299 and only saw other issues with the action

**Comment by actboy168** [comment]
@thboop My action will add my own ninja to the path and execute it. Then there is ninja in the host, if add-path fails, the default ninja will be executed.This is the error message you see.

**Comment by HunterZ** [comment]
So is this deprecated or not? It's still in the readme...
