### ISSUE TITLE
Fix toolkit by not using depracated add-path command

### ISSUE THREAD

**Issue by uwehdaub** [actions/toolkit#643]
See here https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L67

This will break any action using the core package with this command.

**Comment by thboop** [comment]
This is already resolved, please update to the latest version of `@actions/core` 1.2.6. 

The code you linked to was put in for back-compat for older runners which don't support environment files, it will eventually be removed.

**Comment by umitkutlu1** [comment]
Ümit
