### ISSUE TITLE
Package release process

### ISSUE THREAD

**Issue by chrislennon** [actions/toolkit#66]
👋 Noticing there is some differences between the published `1.0.0` versions of the packages that are published on npm and the code in master. One specific thing was the features added on #49 

Currently working around this with a fork of just the tool-cache package so I can test a matrix build of [an action](https://github.com/chrislennon/action-aws-cli) I'm working on.

Would be awesome if we can get publishes on merges to master (or some other awesomeness) 🎉 ❤️

**Comment by damccorm** [comment]
Sorry we haven't published yet! I added #67 to get consensus on publishing, once that's in I'll publish `@actions/tool-cache` at `1.1.0`

**Comment by damccorm** [comment]
Published! https://www.npmjs.com/package/@actions/tool-cache
