### ISSUE TITLE
"Error: TypeError: Expected signal to be an instanceof AbortSignal" when retrieving cached files

### ISSUE THREAD

**Issue by tetchel** [actions/toolkit#687]
I've written an action which downloads a number of executables and caches them using `@actions/cache`:
https://github.com/redhat-actions/openshift-cli-installer/

Workflow here:
https://github.com/redhat-actions/openshift-cli-installer/runs/1670875424

```
Checking the cache for helm 3.1.3...
##[debug]Resolved Keys:
##[debug]["oci_helm_3.1.3_linux_amd64"]
##[debug]Checking zstd --version
##[debug]*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/KuUXHpFvGOy0aS8vdXRfkYqXmiHMnxoJXt9OW4bxjm3HMLBzYK/_apis/artifactcache/cache?keys=oci_helm_3.1.3_linux_amd64&version=a3496a09f37d31c59c6f157823a74f6311019c9abfd35c16c1887b169b0251c2
::add-mask::***
##[debug]Cache Result:
##[debug]{"scope":"refs/heads/main","cacheKey":"oci_helm_3.1.3_linux_amd64","cacheVersion":"a3496a09f37d31c59c6f157823a74f6311019c9abfd35c16c1887b169b0251c2","creationTime":"2021-01-08T20:09:18.4133333Z","archiveLocation":"***"}
##[debug]Archive Path: /home/runner/work/_temp/64dbf1b1-3cdc-4600-983d-d237861f11ae/cache.tzst
##[debug]Use Azure SDK: true
##[debug]Download concurrency: 8
##[debug]Request timeout (ms): 30000
##[debug]Failed to delete archive: Error: ENOENT: no such file or directory, unlink '/home/runner/work/_temp/64dbf1b1-3cdc-4600-983d-d237861f11ae/cache.tzst'
Error: TypeError: Expected signal to be an instanceof AbortSignal
```

I get that same error when fetching any file from the cache.

edit: Edited to remove references to the large file because it is not the cause.

**Comment by tetchel** [comment]
The issue was https://github.com/node-fetch/node-fetch/issues/784 because I switched to webpack. I fixed it with https://github.com/node-fetch/node-fetch/issues/784#issuecomment-618527886 

I suppose the Actions team is all using `ncc`.

**Comment by rnett** [comment]
I'm getting this as well, it would be nice to have an actual fix.

**Comment by tetchel** [comment]
It is a problem with the webpack minimizer (terser plugin) stripping class names, it is not a problem with this library.

**Comment by rnett** [comment]
Yeah, but as node-fetch doesn't seem like they are going to fix it (and I'm not familiar enough with JS to know whether it's even possible), a workaround here would be nice.  Not sure whether that's possible, either.

**Comment by tetchel** [comment]
if you're using ncc, you could probably _not_ pass the `-m/--minify` flag and that may fix it.

**Comment by rnett** [comment]
I'm using webpack, and the workarounds in that thread (the last one at least) work, it's just fragile.
