### ISSUE TITLE
Mocking @actions/github in your tests

### ISSUE THREAD

**Issue by xt0rted** [actions/toolkit#71]
I haven't seen any tests or examples that show how you'd mock `@actions/github` using Jest. How would one go about doing this?

My action contains the following:

```typescript
import { getInput } from "@actions/core";
import { context, GitHub } from "@actions/github";

const client = new GitHub(
  getInput("repo-token", { required: true })
);

var actorAccess: Octokit.Response<CollaboratorPermissionLevel> = await this.client.repos.getCollaboratorPermissionLevel({
  ...context.repo,
  username: context.actor
});

// ...

await this.client.reactions.createForIssueComment({
  ...context.repo,
  comment_id: commentId,
  content: this.reaction.type,
});
```

**Comment by damccorm** [comment]
We don't provide a specific library for mocking, though I'm working on docs that should probably include that. There's kinda 2 sides to this.

The first is the context (e.g. `context.repo`, `context.actor` in this case). This one is easier to mock, you can just set the environment variables that it reads from which you can see [here](https://github.com/actions/toolkit/blob/master/packages/github/src/context.ts).

The second half of this is a little more challenging - mocking the client calls to the GitHub API. On that one, I'd probably defer to the Octokit rest folk (this library builds on top of their client). Their guidance - the best I've found is [here](https://github.com/octokit/rest.js/issues/1251). To summarize, it looks like they maybe want to build out a more complete testing framework, but right now they recommend using [nock](https://github.com/nock/nock) to mock the calls to the GitHub API

**Comment by JasonEtco** [comment]
+1 for using `nock` wherever possible. I've written a ton of tests for code that uses the GitHub API and Octokit, and while mocking the Octokit SDK totally works, it means that tests become dependent on the SDK to have specific methods.

Once those methods change, its hard to update your tests and code at the same time to track those changes. With `nock`, you're writing tests that are more realistic in how your code interacts with the API.

**Comment by d923** [comment]
[nock-next.zip](https://github.com/actions/toolkit/files/3526567/nock-next.zip)

**Comment by xt0rted** [comment]
@damccorm [actions/javascript-template](https://github.com/actions/javascript-template) sets you up with Jest so that's what I was using. I came across nock while looking at [JasonEtco/actions-toolkit](https://github.com/JasonEtco/actions-toolkit) and Octokit since that's what my actions were originally using, just wasn't sure if that was the recommended way to test actions or if mocking the toolkit itself was a better route.

**Comment by damccorm** [comment]
> actions/javascript-template sets you up with Jest so that's what I was using.

Yep - to be clear, those aren't mutually exclusive - you can still use the jest framework and just nock specific http requests.

I'll try to add some docs that talk about this soon!

**Comment by xt0rted** [comment]
I started updating my tests to use the `GITHUB_` environment variables and what I've found is any of them that are used in a constructor end up returning `undefined` but if they're used in a property or function then they return a value.

These "properties" all return `undefined` in my tests https://github.com/actions/toolkit/blob/f66f5629b3f1303cf816b5e1823bae92ff02ece9/packages/github/src/context.ts#L22-L32

While these return data, though `issue` is missing `number` since `payload` is `undefined` https://github.com/actions/toolkit/blob/f66f5629b3f1303cf816b5e1823bae92ff02ece9/packages/github/src/context.ts#L34-L54

If I update this class to use properties instead of setting everything up in the constructor then things work as I'd expect and the custom payload gets loaded.

I'm assuming this is a result of how Jest is sandboxing the tests and/or the modules are being loaded, but it's definitely not the behavior I was expecting to see.

**Comment by damccorm** [comment]
So I ran into this and I think I know why exactly this is happening, I should be clearer in my walkthrough docs though and will update accordingly.

Basically, the issue is that the GitHub class loads its properties (e.g. payload, eventName, sha, etc...) as soon as it is loaded. So the `env` needs to be set before we require the action that requires `@actions/github` - you can see I do that in my walkthrough - https://github.com/actions/toolkit/blob/getting-started-docs/docs/github-package.md#mocking-the-octokit-client

**Comment by xt0rted** [comment]
@damccorm after playing around with this a bit more I found that if I get rid of the `import { CommandHandler } from "../src/commandHandler";` line and then require that in each test after setting up the context, then the environment variables are loaded. This really over complicates the tests though, repeats a ton of code, and I lose type information for what I `require()`. At this point it seems easier to mock the class instead of trying to use the default behavior.

**Comment by damccorm** [comment]
> At this point it seems easier to mock the class instead of trying to use the default behavior.

Yeah, you're probably right. I'll look into updating the docs.

**Comment by ezyang** [comment]
> after playing around with this a bit more I found that if I get rid of the import { CommandHandler } from "../src/commandHandler"; line and then require that in each test after setting up the context, then the environment variables are loaded. This really over complicates the tests though, repeats a ton of code, and I lose type information for what I require(). At this point it seems easier to mock the class instead of trying to use the default behavior.

I think it's worse than that. Because node only ever loads a module once, once you load `action/github` for the first time, the particular environment variables you had used at that point of time are burned in. Which means if you try to write a second test with different environment variables, they will still be stuck with the first setting (unless jest is running your tests in multiple processes, which I suppose is what it does by default). The global singleton is really screwing us over; better to just pass the hydrated github object around.

**Comment by ericsciple** [comment]
Example here: https://github.com/actions/checkout/blob/master/__test__/input-helper.test.ts

Mocks registered in `beforeAll` and unregistered in `afterAll`

**Comment by ryparker** [comment]
> Example here: [actions/checkout@`master`/__test__/input-helper.test.ts](https://github.com/actions/checkout/blob/master/__test__/input-helper.test.ts?rgh-link-date=2019-12-16T18%3A42%3A38Z)
> 
> Mocks registered in `beforeAll` and unregistered in `afterAll`

@ericsciple This is useful however it doesn't demonstrate how we can mock context values such as `issue`, `pull_request`, etc.

Any guidance on how we might implement that with jest?

**Comment by ryparker** [comment]
Never mind I found a solution:

```ts
import * as github from '@actions/github'
import { GithubApi } from '../github';

// Shallow clone original @actions/github context
let originalContext = { ...github.context }

afterEach(() => {
  // Restore original @actions/github context
  Object.defineProperty(github, 'context', {
    value: originalContext,
  });
})


test('sets issueNumber, when initialized with an issue payload', () => {
  // Mock the @actions/github context.
  Object.defineProperty(github, 'context', {
    value: {
      payload: {
        issue: {
          number: 12345,
        },
      },
    },
  });
  const githubApi = new GithubApi('GITHUB_TOKEN');

  expect(githubApi['issueNumber']).toStrictEqual(12345);
});
```

**Comment by cchanche** [comment]
So after trying a quadrillion solutions that would not work, here is what did the trick for me.

Just make sure the environment variables are ready before you `import` or `require` `@actions/github`. (ex: `GIHUB_EVENT_PAYLOAD`, `GITHUB_REF` as described in [the variable reference](https://docs.github.com/en/actions/reference/workflows-and-actions/variables)). I used [mocked-env](https://www.npmjs.com/package/mocked-env).

And the following may sound trivial to Jest veterans out-there, but you may need to clear your import cache before (or after) each test to do this.

> [!note]
> Mocking the octokit client does work fine with [nock](https://www.npmjs.com/package/nock) for me. This is about mocking the context.

```typescript
import mockedEnv, { RestoreFn } from 'mocked-env'

/**
 * Helper to run the action in an isolated module context.
 * Especially useful for `@actions/github` which reads from process.env
 * at import time.
 */
const run = (...args) =>
  jest.isolateModulesAsync(async () => {
    await (await import(`../src/main.js`)).run(...args)
  })

describe('my-module', () => {

  afterAll(() => {
    jest.resetAllMocks()
  })
  
  describe('on push event', () => {
    let restore: restore

    beforeEach(() => {
      restore = mockedEnv({
        GITHUB_EVENT_NAME: 'push',
        GITHUB_EVENT_PATH: pathToPushPayload,
        GITHUB_REF: pushPayload.ref,
      )};
    })
    
    afterEach(() => {
      restore();
    })
    
    it('does stuff', async () => {
      await run(); // will make a fresh import of `@actions/github`
    
      expect(stuff).toBeDone();
    })
  })

  describe('on pull_request event', () => {
    let restore: restore

    beforeEach(() => {
      restore = mockedEnv({
        GITHUB_EVENT_NAME: 'pull_request',
        GITHUB_EVENT_PATH: pathToPRPayload,
        GITHUB_REF: PRPayload.ref,
      )};
    })
    
    afterEach(() => {
      restore();
    })
    
    it('does stuff', async () => {
      await run(); // will make a fresh import of `@actions/github`
    
      expect(stuff).toBeDone();
    })
  })
})

```
