### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by mambax** [actions/toolkit#722]
**Describe the bug**
Where can I find the TypeDefinitions? In my optimal world, a TypeScript project uses Types. But I struggle really badly to teach my VSCode all the examples from this repo. Sorry for the ultra dumb question but how can I properly set up an action with TS?

**To Reproduce**
1. Use the Typescript Template
2. Open in VSCode
3. Try to edit any example and use some of the content of the examples

**Expected behavior**
I can import TypeDefinitions, my simple example would be, how can I get a typed Repository?
```
import * as github from '@actions/github'
const context = github.context
const repo: PayloadRepository (this does not exist) = context.payload.repository
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5472171/108565901-c90c7680-7305-11eb-9168-4c5cf3d7cba6.png)
or
![image](https://user-images.githubusercontent.com/5472171/108566625-032a4800-7307-11eb-8b44-7c2755c8735a.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 88.0.4324.182

**Additional context**

**What I try to do anyway?**

I seem like I miss the simplest of all puzzle parts, miss the tree standing in front of the wood. How can one typed develop a TS Action?

Why I ask, I try to Typscriptify and then adapt [this action](https://github.com/lots0logs/gh-action-get-changed-files). My action is (in the broken state) [here](https://github.com/mambax/touched-files).

How would I get my hands on the list of commits like [him](https://github.com/lots0logs/gh-action-get-changed-files/blob/002a3dec1083f13f4e1853c5c1dc26526ac185bc/index.js#L47) but **typed**? 😢 

Can someone enlighten me?

Sorry if this is in the wrong place, happy to go to a new place to ask if someone tells me where 🏃

**Comment by peaceiris** [comment]
```ts
import {context} from '@actions/github';

const eventName = context.eventName;
```

e.g. https://github.com/peaceiris/actions-label-commenter/blob/1d4d794ae29289cc6561faf5bace92647f174c07/src/main.ts

**Comment by mambax** [comment]
Thanks for your reply @peaceiris. But I still cant follow how e.g. one should make this work:

```js
export async function getCommits(): Promise<string[]> { // is that even the correct returnt type?
  let commits: string[]
  debug('Getting commits...')
  switch (context.eventName) {
    case 'push':
      commits = context.payload.commits // ?? What type are commits? Where can I find them?
      break
    case 'pull_request':
      commits = await gh.paginate(
        `GET ${context.payload.pull_request?.commits_url}`, // same
        args
      )
      break
    default:
      info(
        'You are using this action on an event for which it has not been tested. Only the "push" and "pull_request" events are officially supported.'
      )
      commits = []
      break
  }
  return commits
}
```

What is a commit? A string? A commit object? What type? 😢

**Comment by peaceiris** [comment]
As you see my project, I am using [octokit/webhooks: machine-readable, always up-to-date GitHub Webhooks specifications](https://github.com/octokit/webhooks#readme).

**Comment by tonyhallett** [comment]
See https://github.com/actions/toolkit/pull/743
