### ISSUE TITLE
listTar (enabled by debug mode) becomes very verbose in case of large repos like a node.js monorepo

### ISSUE THREAD

**Issue by sgronblo** [actions/toolkit#729]
If your issue is relevant to this repository, please include the information below:

**Describe the bug**
Maybe could be considered a feature request as well. As stated in the title, a recent change to `@actions/cache` added a call to `listTar` in case `core.isDebug()` is true. This change can be seen here: https://github.com/actions/toolkit/commit/bfdba95ecee3430fb9010832a0bdda9f1b0aaf06#diff-34e72845d1658a8a9b9fdfe6b5b9261952e7f0496a0a3fcec87dae722718a64aR171

My current project uses Cypress with a monorepo and we have enabled debug for seeing debug output from other actions such as `@cypress-io/github-action`. However, the cypress action additionally tries to cache your npm/yarn folder. In this case you will see the contents of all the files in all your node_modules as part of your test output. In our case this is close to 100k of additional lines that slow down the GH action result viewer. It would be nice if the call to `listTar` was controllable through another flag in addition to core.isDebug so we could avoid this.

**To Reproduce**
1. Create a node.js monorepo and add a large amount of node_modules dependencies
2. Add cypress tests
3. Setup the @cypress-io/github-action plugin for your repo
4. Enable debugging by creating a secret called `ACTIONS_STEP_DEBUG` with the value true
5. Trigger a test run
4. Check the output in GH

**Expected behavior**
Every file in node_modules should not be shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: @actions/cache@1.0.6

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**

**Comment by sgronblo** [comment]
To be more specific, the cypress action is not caching your node_modules folder, it caches your yarn/npm cache folder.

**Comment by thboop** [comment]
Hey @sgronblo , I understand the pain here, but we are unlikely to add individual outputting debug tuning on functions in the toolkit in the near future.

**Comment by bahmutov** [comment]
@sgronblo I am switching Cypress GH Action to use `debug` module here https://github.com/cypress-io/github-action/pull/379
