### ISSUE TITLE
Unclear Instructions: Where does example code from javascript-action go?

### ISSUE THREAD

**Issue by bnb** [actions/toolkit#73]
Hello!

I'm trying to follow along in [javascript-action.md](https://github.com/actions/toolkit/blob/master/docs/javascript-action.md), which has several code examples. Specifically, lines 19-22 and 46-58.

I'd love to use these examples, except for me (as a first-time Action author) it's entirely unclear where they're supposed to go.

Clarifying that inside of the document would be ideal.

**Comment by radu-matei** [comment]
Hey!
(Not working on the team building Actions, just tagging along 😄)

If you create a repo based on https://github.com/actions/javascript-template, then the file you're looking for is `action.yml`.

Hope this helps!

**Comment by bryanmacfarlane** [comment]
Here's the new doc: https://github.com/actions/javascript-action/README.md

I supposed that has the same issue?  Should we just not to edit the index.js file?

**Comment by bryanmacfarlane** [comment]
The new javascript action walkthrough makes it clear.
