### ISSUE TITLE
actions url contains branch

### ISSUE THREAD

**Issue by soloturn** [actions/toolkit#731]
currently the actions for a branch are exposed via a url parameter, e.g. [https://github.com/actions/toolkit/actions?query=branch%3Aadd-path] (https://github.com/actions/toolkit/actions?query=branch%3Aadd-path).

this is not very practical to display the branch dynamically, e.g. in documentation files, e.g. the status of an action out of a readme, this full path needs to be given. much nicer would be a url which allows going up until a branch is reached like is the case when displaying source code links. which can be done with /LICENSE.txt, or [../actions/workflows/unit-tests.yml](../actions/workflows/unit-tests.yml)

(most likely this is the wrong repository to file this, if you could direct this to the correct one please)

**Comment by thboop** [comment]
Hey @soloturn , please file an issue in the [community forums](https://github.community/c/code-to-cloud/github-actions/41)
