### ISSUE TITLE
exec.exec() and core.setFailed() do not fail build

### ISSUE THREAD

**Issue by fniephaus** [actions/toolkit#737]
Our [`setup-smalltalkCI`](https://github.com/hpi-swa/setup-smalltalkCI) action installs some dependencies via `apt-get` using the following expression:

```
await exec.exec('sudo apt-get update')
```

Even though the outer `run` function contains a `try-catch` block that calls [`core.setFailed()`](https://github.com/hpi-swa/setup-smalltalkCI/blob/v1/index.js#L75) in case of errors, the build does not fail there (see [here](https://github.com/tom95/sandblocks/runs/2113619481?check_suite_focus=true#step:3:59)).

How can we make sure that builds fail early, so that our users are not confused by later errors that come, for example, from a failing `apt-get`?

Related issue: #390

/cc @tom95

**Comment by luketomlinson** [comment]
Thank you for submitting an issue @fniephaus! I did some digging, but I was unable to reproduce this issue using a small example. 

```typescript
import * as core from '@actions/core'
import * as exec from '@actions/exec'

async function run(): Promise<void> {
  try {
    
    await exec.exec('./fail-now.sh')
    
  } catch (error) {
    core.setFailed(error.message)
  }
}

run()

```

fail-now.sh
```bash
echo 'Running fail-now.sh'
exit 100
```

When I run this workflow I get a failure output as expected. 
<img width="994" alt="Screen Shot 2021-05-03 at 2 41 25 PM" src="https://user-images.githubusercontent.com/19689611/116918317-becbfa00-ac1d-11eb-9a1e-a6f92bfc8c8f.png">

Is this issue still occurring for you?

**Comment by fniephaus** [comment]
Thanks for checking, @luketomlinson! It turned out that an [`aware` was missing](https://github.com/hpi-swa/setup-smalltalkCI/commit/a89a05efc1acb01977b6acf27bd1fa506cacaacb) and now builds fail early when `apt-get` fails (see [here](https://github.com/hpi-swa/setup-smalltalkCI/runs/2574937793?check_suite_focus=true#step:3:10)).

Sorry for the noise!

**Comment by luketomlinson** [comment]
No worries @fniephaus. Glad you got it sorted out 😄
