### ISSUE TITLE
Run workflow button

### ISSUE THREAD

**Issue by andreaslarssen** [actions/toolkit#739]
**Describe the bug**
When clicking the green "Run workflow" button in the pop up box, it does not indicate that the workflow has been initialized. 

This can lead to multiple workflows being started, as there's no way to confirm that the action is processing.

The button should show some kind of indicator that the workflow has been started, or the very least be disabled. 

Alternatively, and maybe even better, close the box the button is in as soon as the button is clicked, and add a line in the workflow list that indicates that it has been initialized.

**Comment by thboop** [comment]
Hey @andreaslarssen , can you make a post in the [community forums](https://github.community/c/code-to-cloud/github-actions/41) this is unrelated to the toolkit? Providing screenshots would be helpful as well!

**Comment by andreaslarssen** [comment]
@thboop Ah, my bad. Will do, thanks.
