### ISSUE TITLE
Select box input for choosing tag or branch to deploy

### ISSUE THREAD

**Issue by andreaslarssen** [actions/toolkit#740]
**Describe the enhancement**
It would be nice to be able to present the dev with a dropwdown / select box w/ all tags and / or branches so that they can click-and-choose what to deploy. I can't find a way to set this up, so I ended up w/ an input field that takes a ref. Not optimal.

**Additional information**
Screenshot of our current setup:
![Workflow](https://user-images.githubusercontent.com/3169836/111464687-6a2df780-8721-11eb-9813-7814892e3fbb.png)

Inspiration from Envoyer:
![envoyer](https://user-images.githubusercontent.com/3169836/111464684-67cb9d80-8721-11eb-88f6-34ff0412a0e9.png)

**Comment by thboop** [comment]
Hey @andreaslarssen can you file this in the [community forums](https://github.community/c/code-to-cloud/github-actions/41) we can't fix this in the toolkit

**Comment by andreaslarssen** [comment]
@thboop Will do that for this one as well, thanks
