### ISSUE TITLE
Don't create basename directory if copying directory into existing one

### ISSUE THREAD

**Issue by BetaHuhn** [actions/toolkit#741]
**Current implementation/problem**

I want to copy the contents of a directory into another existing directory. Right now, because of these lines:

https://github.com/actions/toolkit/blob/4dd900dde00dcc90e5c649b688c643b1fc7684a2/packages/io/src/io.ts#L47-L51

The files/folders in the source directory get copied into another folder (the basename of the source path) inside the target directory.

For example, I want to copy the directory `.github/ISSUE_TEMPLATE/` to `issues/`. With the current version of [`@actions/io`](https://github.com/actions/toolkit/tree/main/packages/io) the files will end up in `issues/ISSUE_TEMPLATE` instead of `issues/` if `issues/` already exists.

**Describe the enhancement**

Add an option to disable this behavior and copy all files from one directory into the other without creating the basename folder.

**Code Snippet**

```js
const newDest: string =
    destStat && destStat.isDirectory() && copyInside // Add this new option
      ? path.join(dest, path.basename(source))
      : dest
```

**Additional information**

If there's another way of achieving this, please let me know. If not, I would be willing to create a PR for this.

**Comment by KELLZ77** [comment]
Hi I'm having some troubles with ppl helping themselves out at . I'm not
savvy on that sorta thing and any help would be so appreciated .Is that
what is going on? And how to tell

**Comment by wsiim** [comment]
But I'm sure you will have me

**Comment by BetaHuhn** [comment]
Great, thanks!
