### ISSUE TITLE
Status badge has wrong width when workflow name contains Unicode 🦄

### ISSUE THREAD

**Issue by LinqLover** [actions/toolkit#742]
**Describe the bug**
If a workflow name contains Unicode characters, the width for the status badge is too small:

![image](https://user-images.githubusercontent.com/38782922/111675159-1c96b500-881d-11eb-9e42-773154cda588.png)
https://github.com/hpi-swa-lab/SqueakByExample-english/actions/runs/665402056

**Comment by thboop** [comment]
Hey @LinqLover , this isn't related to the toolkit. I've let the team in charge of this know, but can you make a post in the [community forums](https://github.community/c/code-to-cloud/github-actions/41) about this to report the bug?

**Comment by LinqLover** [comment]
Alright, I have re-reported the issue here: [[BUG] Status badge has wrong width when workflow name contains Unicode 🦄](https://github.community/t/bug-status-badge-has-wrong-width-when-workflow-name-contains-unicode)
