### ISSUE TITLE
@actions/http-client@1.0.10 released without build

### ISSUE THREAD

**Issue by nogic1008** [actions/toolkit#747]
**Describe the bug**
`@actions/http-client@1.0.10` contains TypeScript files directly, and no JavaScript codes.
We cannot use this package from JavaScript project.

**To Reproduce**
1. `npm i @actions/http-client@1.0.10`
2. `ls node_modules/@actions/http-client`

**Expected behavior**
Release with compiled code

**Screenshots**
![folder structure](https://user-images.githubusercontent.com/24802730/112405026-d4175400-8d54-11eb-88fc-9aadd36e3423.png)

**Comment by bryanmacfarlane** [comment]
This is fixed now with a 1.0.11 release.  Apologies for the inconvenience.  Thanks for filing the issue.
