### ISSUE TITLE
Easier to get command output

### ISSUE THREAD

**Issue by cobraz** [actions/toolkit#769]
**Describe the enhancement**

There are a few Github Actions that require the command output, like [docker/build-push-action](https://github.com/docker/build-push-action/blob/master/src/exec.ts), [bjerkio/kopier](https://github.com/bjerkio/kopier/blob/9ec42c990dfd6ee394a4b16d0be2b054259552d3/src/git-commit.ts#L25-L47) and [pulumi/action](https://github.com/pulumi/actions/blob/master/src/libs/exec.ts).

I've personally added this functionality twice so far, so I thought it might be something we should consider adding to `@actions/exec` directly?

**Code Snippet**

```typescript
import { getCommandOutput } from '@actions/exec';

const output = await getCommandOutput('echo', ['hello', 'world']);

// output = "hello world"
```

**Comment by rcowsill** [comment]
Here's another implementation of that functionality: https://github.com/satackey/actions-exec-listener

**Comment by cobraz** [comment]
> Here's another implementation of that functionality: [satackey/actions-exec-listener](https://github.com/satackey/actions-exec-listener)

Thank you so much for sharing that, @rcowsill!
