### ISSUE TITLE
Unecessary newlines added to console output

### ISSUE THREAD

**Issue by crazy-max** [actions/toolkit#777]
#772 adds newlines in step console output which seems not right to me.

Before this change:

![image](https://user-images.githubusercontent.com/1951866/115746311-86fac200-a394-11eb-8298-f2caafca890c.png)

After:

![image](https://user-images.githubusercontent.com/1951866/115746265-7a766980-a394-11eb-91d7-c0ede0891f29.png)

Another example with [consecutive setOutput used programmatically](https://github.com/docker/setup-buildx-action/blob/0dcbadd8d09951419743fe2dd497847bd825b108/src/main.ts#L75-L79):

![image](https://user-images.githubusercontent.com/1951866/115746411-9da11900-a394-11eb-9e86-fe425ee8d0f8.png)

Could it be filtered out please or at least optional?

cc. @ericsciple

Thanks

**Comment by thboop** [comment]
The runner processes line by line so we won't be able to filter this line out without completely revamping that process, which is unlikely to be done in the near future.

We could instead add a comment that we are setting the output, does that sound better to you?

**Comment by crazy-max** [comment]
@thboop 

> We could instead add a comment that we are setting the output, does that sound better to you?

Yes sounds better. This modification was about a security issue?

**Comment by vers-one** [comment]
As a workaround, you can do something like this:
```
console.log("::set-output name=my-output::my-value");
```
which is equivalent to:
```
core.setOutput("my-output", "my-value");
```
but doesn't output any empty lines to the log.

Sure, it's a hack but in my opinion the whole idea to use the standard output both for logging and for communication with the runner wasn't the best design choice in the first place.

**Comment by paescuj** [comment]
This should be "fixed" by https://github.com/actions/toolkit/pull/1178, right?

**Comment by crazy-max** [comment]
@paescuj https://github.com/actions/toolkit/blob/4fbc5c941a57249b19562015edbd72add14be93d/packages/core/src/core.ts#L198

**Comment by paescuj** [comment]
@crazy-max
https://github.com/actions/toolkit/blob/3a95e19ebd9de276354a7b4f7a0b98dd8580590b/packages/core/src/core.ts#L193-L196

**Comment by crazy-max** [comment]
@paescuj 

Looks like `GITHUB_OUTPUT` is not yet available on GitHub Runners when dumping env vars: https://github.com/crazy-max/ghaction-dump-context/actions/runs/3017190624/jobs/4850763782#step:3:10

**Comment by paescuj** [comment]
It seems like the workflow run you referenced has been executed 29 days ago. The public runners have been updated in the meantime and - at least in my case - the change introduced in https://github.com/actions/toolkit/pull/1178 is working properly, see for example https://github.com/fkirc/skip-duplicate-actions/pull/285.

**Comment by crazy-max** [comment]
Ah indeed looks good:
* https://github.com/crazy-max/ghaction-dump-context/actions/runs/3211018814/jobs/5248887556#step:1:1
* https://github.com/crazy-max/ghaction-dump-context/actions/runs/3211018814/jobs/5248887556#step:3:47
