### ISSUE TITLE
When are these packages released?

### ISSUE THREAD

**Issue by shrink** [actions/toolkit#806]
Apologies if I'm missing something obvious, but there's a new feature I want to use (`getBooleanInput`) that has been merged into main a few weeks ago, but it's not clear how/when that'll be released. According to the repository [releases](https://github.com/actions/toolkit/releases) there hasn't been any releases for a long time, but according to [npm](https://www.npmjs.com/package/@actions/core) there was a release a month ago. 

How do the releases of the packages in this repository happen, are they scheduled, or is it adhoc?

Thanks,

**Comment by thboop** [comment]
Hey @shrink , they are pretty adhoc, I'll get that feature released early next week!
