### ISSUE TITLE
default defined in action.yml not being read by getInput command in @actions/core

### ISSUE THREAD

**Issue by artis3n** [actions/toolkit#813]
**Describe the bug**
Recent releases of [my GitHub action](https://github.com/artis3n/ansible_galaxy_collection) began failing soon after merging `@actions/core` version 1.2.7 (maybe unrelated? I merged updates and bumped the action from node 14 to 16 and this failure occurred after that). The [errors](https://github.com/robertdebock/ansible-collection-roles/runs/2619893143#step:4:5) (better debugging in [this example](https://github.com/artis3n/test-ansible-collection/runs/2626673168?check_suite_focus=true#step:4:5) were due to the command `getInput('galaxy_config_file')` returning an empty string even though the `galaxy_config_file` parameter in my `action.yml` has a `default` value applied.

**To Reproduce**
Not too sure why this is happening. My hypothesis was that setting the `default` value and moving `required` to false somehow broke it but I was not able to reproduce that on a fresh template - https://github.com/artis3n/actions-core-1.2.7-default-bug/commits/main .

How I can reproduce on my action:
1. Fork this PR - https://github.com/artis3n/ansible_galaxy_collection/pull/142
2. Checkout commit `faba15c5f2be6fec1625858d72a3e94cbcc571c7` to see the behavior but with better logging
3. Note the following in the source code:

    a. Source: https://github.com/artis3n/ansible_galaxy_collection/blob/faba15c5f2be6fec1625858d72a3e94cbcc571c7/src/main.ts#L22
    b.Sink: https://github.com/artis3n/ansible_galaxy_collection/blob/faba15c5f2be6fec1625858d72a3e94cbcc571c7/src/main.ts#L70

4. Build the action from that commit hash or leverage the snapshot I build off that commit - https://github.com/artis3n/ansible_galaxy_collection/runs/2626650351#step:5:443 (<https://github.com/users/artis3n/packages/container/ansible_galaxy_collection-testartifact/2629525?tag=SNAPSHOT-79ea1722a693bdae4039ae3cfc3477bacc9db3cd>)
5. Observe the error produced by that snapshot reveals that `galaxy_config_file` is an empty string instead of the default value: https://github.com/artis3n/test-ansible-collection/runs/2626673168?check_suite_focus=true#step:4:5
6. Now checkout the latest commit in my PR, currently `7649a6a480d33b62f1d9e3a906a2293bc7797d44`.
7. Note the only change from the previous commit is adding a default ` || 'galaxy.yml'` value after the `getInput` call, which shouldn't be necessary if the default value is picked up. (<https://github.com/artis3n/ansible_galaxy_collection/pull/142/commits/7649a6a480d33b62f1d9e3a906a2293bc7797d44#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR22>)
8. That publishes this snapshot: https://github.com/artis3n/ansible_galaxy_collection/pull/142/checks?check_run_id=2626685183#step:5:445 (<https://github.com/users/artis3n/packages/container/ansible_galaxy_collection-testartifact/2629591?tag=SNAPSHOT-9331436dafa69b166cc5cd380fc48f59e3a16f1e>)
9. Observe that snapshot results in, well, a different error but an error that occurs after successfully using the `galaxy.yml` value provided by `|| 'galaxy.yml'`. (<https://github.com/artis3n/test-ansible-collection/runs/2626702592?check_suite_focus=true>)

    a. This errors occurs from [this section](https://github.com/artis3n/ansible_galaxy_collection/blob/fix-broken-action/src/main.ts#L49) of the code, after the `galaxy_config_file` parameter variable is used, for what it is worth.

**Expected behavior**
```yml
getInput('galaxy_config_file')
```
results in the default value `galaxy.yml` as it is defined in `action.yml` according to the documentation: <https://github.com/actions/toolkit/tree/main/packages/core#inputsoutputs>

> If required set to be false, the input should have a default value in action.yml

**Screenshots**
See linked action workflow runs in the reproduction

**Desktop (please complete the following information):**
 - OS: PopOS! 20.10
 - Browser: Firefox
 - Version: 88.0.1

**Smartphone (please complete the following information):**
N/A

**Additional context**

None

**Comment by luketomlinson** [comment]
hi @artis3n, I dug into this, and I was curious if you were able to get it working outside of your `|| 'galaxy.yml` workaround? Your test repo seems to be [working as expected](https://github.com/artis3n/test-ansible-collection/actions/runs/862543579)?

I am not sure this is an issue with `@actions/core` as no updates to `getInput` were made from [1.2.6](https://github.com/actions/toolkit/commit/a5e05630d8e1d89cd75b5a12a972daae8abc6e1a#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7) and [1.2.7](https://github.com/actions/toolkit/commit/e76decaf8a52bc981d17ddd3efcca548f6bc1a0e#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7)

**Comment by artis3n** [comment]
I used the `|| 'galaxy.yml'` as the workaround, did not find another solution. I also can't really see how actions/core would have broken this but I don't see what else is the problem - I previously logged the values directly after the `getInput` function and the supposed defaults were empty strings.

**Comment by luketomlinson** [comment]
Gotcha @artis3n. So from your example [here](https://github.com/artis3n/test-ansible-collection/actions/runs/862543579) it seems the most recent change was working? Is this problem intermittent?

**Comment by luketomlinson** [comment]
ahh so @artis3n. I realized you are using Docker for your action. I believe you aren't passing the inputs to the docker container as documented [here](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file). Your [Dockerfile](https://github.com/artis3n/ansible_galaxy_collection/blob/3668a2ba24c636257bc4c52c20d87062dbd949f4/action.yml#L44) doesn't seem to have the `args` parameter.

**Comment by artis3n** [comment]
> ahh so @artis3n. I realized you are using Docker for your action. I believe you aren't passing the inputs to the docker container as documented [here](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file). Your [Dockerfile](https://github.com/artis3n/ansible_galaxy_collection/blob/3668a2ba24c636257bc4c52c20d87062dbd949f4/action.yml#L44) doesn't seem to have the `args` parameter.

Ah, that is interesting. I wonder how https://github.com/artis3n/ansible_galaxy_collection/blob/main/.github/workflows/main.yml#L49 works if I am not forwarding the arguments - the action [does use the value](https://github.com/artis3n/ansible_galaxy_collection/runs/2652521019?check_suite_focus=true#step:4:61) from the variable relative to [the default if the parameter is not included](https://github.com/artis3n/ansible_galaxy_collection/runs/2652521019?check_suite_focus=true#step:3:455).

Regardless, I will update my action to that documentation and see if that affects the behavior.

**Comment by artis3n** [comment]
I don't know that that actually matters for a javascript action inside a Docker container - upon invocation the inputs are available to the workflow so they are picked up by [getInput](https://github.com/actions/toolkit/tree/main/packages/core#inputsoutputs). As far as my understanding goes.

**Comment by luketomlinson** [comment]
yeah I believe internally `getInput` is grabbing `INPUT_YOUR_VARIABLE` env variables, so I think your Docker container would need to have those injected.

**Comment by artis3n** [comment]
So - I tried the latest version of my action with the `args` defined in `action.yml` and without. I was unable to reproduce this issue - both versions passed.
https://github.com/artis3n/test-ansible-collection/runs/2660695443?check_suite_focus=true
https://github.com/artis3n/test-ansible-collection/runs/2660720339?check_suite_focus=true

That reinforces my belief that the `args` input is not necessary for this Action, as well as the fact that that requirement would completely break the alternative use option: `uses: docker://artis3n/ansible_galaxy_collection@...`

However, without being able to reproduce it anymore I'm going to :shrug: and we can close this issue. Not sure what was going on.

**Comment by artis3n** [comment]
Ah haa, it is the built docker image that fails to get the defaults, perhaps due to the missing `args`. Let's see - https://github.com/artis3n/test-ansible-collection/runs/2660793256?check_suite_focus=true#step:4:6

**Comment by artis3n** [comment]
However adding the inputs (https://github.com/artis3n/ansible_galaxy_collection/pull/150/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R45) does not fix the issue when using a built Docker image for the action, defaults are not applied: https://github.com/artis3n/test-ansible-collection/runs/2660839387?check_suite_focus=true#step:4:5

So I guess if you would like to use the `uses: docker://` syntax to run an action, you can't rely on defaults passed in from `actions.yml`, not a `actions/core` issue. I recommend somewhere in the documentation should cover this case.

**Comment by artis3n** [comment]
Yup - the `|| 'action.yml'` lets the built docker image function. https://github.com/artis3n/test-ansible-collection/runs/2660923003?check_suite_focus=true#step:4:9

I don't see this caveat in the documentation - https://docs.github.com/en/actions/guides/publishing-docker-images .

**Comment by luketomlinson** [comment]
Thanks for testing all these scenarios @artis3n. I am going to close those for now as this is not a toolkit issue. I will dig into why the defaults aren't showing up the way we expect.
