### ISSUE TITLE
Support private repositories for GitHub Actions

### ISSUE THREAD

**Issue by nathany** [actions/toolkit#88]
I copied [the JavaScript template](https://github.com/actions/javascript-template) over to a private repository and then added the action to another repo: `- uses: aai/cache@v1`.

This is the log output:

```
Download action repository 'aai/cache@v1'
##[warning]Failed to download action 'https://api.github.com/repos/aai/cache/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 27.679 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/aai/cache/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 14.294 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

[Choosing a location for your action](https://help.github.com/en/articles/about-actions#choosing-a-location-for-your-action) only covers using public repositories for GitHub Actions, or putting the action in the repository using the action. So I'm not surprised what I'm trying to do didn't work, but I'm wondering if there are any plans to support this use case?

**Comment by damirstuhec** [comment]
+1 for this. Pretty much every organization has multiple private repositories and being able to reuse in-house actions across multiple private repositories is a must-have, in my opinion.

**Comment by damirstuhec** [comment]
@damccorm I've tried moving our custom action in one of our private repositories as you suggested: `{repo root}/folder1/folder2/{here is where action.yml, src, lib and other files are}`.

I also updated the `uses` in the workflow to `uses: ./folder1/folder2` but I get the following error when the workflow runs:
```
##[error]Can't find 'action.yml' or 'Dockerfile' under '/home/runner/work/{org}/{repo}/folder1/folder2'.
```
Any ideas?

**Comment by damirstuhec** [comment]
That was it! Thank you @damccorm.

**Comment by damirstuhec** [comment]
Is there a plan to support this in the future?

**Comment by chrispat** [comment]
At somepoint in the future we may support this but it is not on our near term backlog.

**Comment by danechitoaie** [comment]
That's very disappointing to hear.  We were planning to use GitHub actions in favor of Jenkins but since migrating the custom Jenkins plugins to GitHub actions that we were using will mean we'll have to make them public this is a dealbreaker so we'll have to stay on Jenkins from what it seems.

**Comment by felipefrocha** [comment]
It should support this spetially that we need some private configurations for jobs, and it is useless if I had to make tons of inputs for hardcoded staff like URL etc
