### ISSUE TITLE
README improvement proposal

### ISSUE THREAD

**Issue by JasonEtco** [actions/toolkit#89]
Hey folks! I wanted to suggest some improvements to the README for this repo, to help folks get started using the toolkit. I can open a PR, but it may take some time to find the bandwidth to do it right - so in the meantime, below is a proposed outline.

### Goals

* Clarify the different packages
  * What each one is, why they're separate
* Show examples of common tasks (ie: reading from the event payload, accessing an input)
* Make the entrypoint for the repo more _action_able.

### Outline

No content suggestions for the first bit:

* Awesome logo
* Description: "The GitHub Actions Toolkit provides a set of packages to make creating actions easier and drive consistency."
* Packages (the existing table)

> Then, a smaller link to the JS template:

<h3 align="center">Get started with the <a href="#">javascript-template</a>!</h3>

* Usage

> When viewing the README, I think we need to show more detail about _using_ the toolkit. I realize that because its mixed between different packages, usage will vary - but showing is better than telling for tools like this. A **rough** outline of what those examples could be:

#### Get an input from the workflow

Using the `@actions/core` library, we can interact directly with the Actions runtime to access logging, workflow inputs and set outputs.

```yaml
steps:
  - uses: actions/hello-world
    with:
      name: octocat
```

```js
const core = require('@actions/core')
const name = core.getInput('name')
console.log(`Hello ${name}!`)
```

#### Read from the event payload

```js
const { context } = require('@actions/github')
console.log(context.payload)
```

#### Make an API request to GitHub

```js
const { GitHub } = require('@actions/github')
const octokit = new GitHub(process.env.GITHUB_TOKEN)
await octokit.issues.create({
  title: 'Example',
  owner: context.repo.owner,
  repo: context.repo.repo
})
```

#### Run a JavaScript file in the repo

```js
const file = `${process.env.GITHUB_WORKSPACE}/index.js`
await exec.exec(`node ${file}`)
```

> Note that all of those examples are in JavaScript, not TypeScript. I think its important to show that TS isn't _necessary_, and given the need to check in the compiled JS files (which I realize y'all are working to improve on), I think it'll really help make the toolkit feel more approachable.
> 
> Continuing with the outline!

* Appendix

> This would include all of the very helpful doc links at the bottom of the current README.

---

These are all suggestions - y'all can take or leave all or none :smile: If I can open a PR I will, but please feel free to implement them.

cc @chrispat

**Comment by bryanmacfarlane** [comment]
@JasonEtco, great suggestions!  I will pick this item up

**Comment by bryanmacfarlane** [comment]
Done.  Thanks!
