### ISSUE TITLE
Allow running the reusable workflow from the same branch

### ISSUE THREAD

**Issue by TWiStErRob** [actions/toolkit#932]
Note: this repo is my best guess for the issue, as it seems `workflow_call` is [not implemented in this org]( https://github.com/search?q=org%3Aactions+workflow_call)?! Please move it if it's not appropriate.

**Describe the enhancement**
Allow using the same branch for `workflow_call`.

Fully-qualified / cross-repo reusability is awesome, but the base case of reusing locally is missing. To develop/change a `workflow_call` I need to update all the usages to test it, imagine the same in programming and method calls 😒.

At the minimum please add this to https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#limitations

**Code snippet**
Right now we [have to use a specific ref](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_iduses):
```yml
jobs:
  caller:
    uses: org/repo/.github/workflows/file.yml@ref
```

For development and stability, it would be best to allow non-qualified usage, for example:
```
uses: org/repo/.github/workflows/file.yml
```
at this point the workflow from the same branch would be used.

SO user makes a good argument here: https://stackoverflow.com/a/69676592/253468

This would only work if it's the same repo, so maybe it could be even simpler as
```
uses: ./.github/workflows/file.yml
```
or just
```
uses: file.yml
```

**Additional information**
https://stackoverflow.com/q/69532525/253468
https://stackoverflow.com/q/69500491/253468

**Comment by sam-myers** [comment]
This is [now available](https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/)!

Taken from source:
```
jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/workflow-2.yml
```

**Comment by TWiStErRob** [comment]
Thanks for the heads up!
Confirmed: https://github.com/TWiStErRob/net.twisterrob.healthcheck/pull/28

GitHub is really unresponsive in this repo :( closing this now in hopes that less open issues will yield more responses. 🤞

**Comment by smallstepman** [comment]
> GitHub is really unresponsive in this repo :( closing this now in hopes that less open issues will yield more responses. 🤞

cc @ossanna16 :( 

I landed here from https://github.com/actions/toolkit/issues/1264

**Comment by marc-hb** [comment]
Unfortunately, it's not possible to use a different branch in the same repo:

```
uses: ./.github/workflows/local-workflow@different-branch

invalid value workflow reference: cannot specify version when calling local workflows
```

Trying to "cheat" and refer to the current repo as if it were a different one results in a super cryptic error:


```
uses: myself/.github/workflows/local-workflow.yml@different-branch

The workflow is not valid. .github/workflows/caller.yml: Unexpected value 'uses'
```

Funnily enough, adding a repo indirection that `uses` back the starting repo shows the same cryptic error.

**Comment by TWiStErRob** [comment]
Just to rule it out: did you refer to `myself` as `org/repo` or just `repo`?

**Comment by marc-hb** [comment]
`org/repo`, otherwise I get the expected: 

```
invalid value workflow reference: references to workflows must be 
prefixed with format 'owner/repository/' or './' 
```

It's only when all the values are correct that I get the cryptic error message. If I make a typo in anything else, I get a useful error message like for instance `should be either a valid branch, tag, or commit`


What really baffles me is this in your description:
> Right now we [have to use a specific ref]
>     uses: org/repo/.github/workflows/file.yml@ref


So when implementing local references, GitHub (accidentally) broke explicit self-references? Are you positive this used to work?

**Comment by marc-hb** [comment]
OK, now I'm getting the same cryptic error after moving the called workflow to a different repository. Maybe it's just an error propagation issue when nesting workflows.

**Comment by marc-hb** [comment]
> Trying to "cheat" and refer to the current repo as if it were a different one results in a super cryptic error:
> Unexpected value 'uses'

My bad, it is possible to do this. I had `runs-on: self-hosted` before `uses:`, that was the actual problem. I really wish GitHub would communicate that better and _before_ parsing the `uses:` parameter; that really threw me off!

Thanks for questioning me, that really helped.


Note the following is still not possible; no confusion about that. That error stands:

```
uses: ./.github/workflows/local-workflow@different-branch

invalid value workflow reference: cannot specify version when calling local workflows
```

So if you want to store your called workflows in a different branch of the same repo, then you must hardcode your entire, own repo name in the calling file. It definitely lacks flexibility and it's not clear why but I'll live with that.

**Comment by TWiStErRob** [comment]
@marc-hb Glad you figured it out.

> What really baffles me is this in your description

I actually don't remember if it worked as my goal was to use it from "current" and not a specific one. I just copied what was available at the time. I updated OP with an archive link, so you can see my context.
