### ISSUE TITLE
Access to feature branch name from Context

### ISSUE THREAD

**Issue by damirstuhec** [actions/toolkit#97]
I'm working on an action that triggers on `issue_comment` and was wondering if there's a way to get ahold of the feature branch from which the comment originated?

I'm currently using `github.context.repo.owner` and `github.context.repo.repo` to access the repo and its owner names but would need a branch name as well.

**Comment by DanTup** [comment]
I'd like access to the branch name generally in the workflow too. I'm porting some things from Travis and I currently upload test results and logs to S3 (to power a web-based dashboard) in a folder `{branch_name}/{hash}` but using `github.ref` results in them going in a folder called `/refs/heads/{branch_name}` which is weird (alternatively, a function that can be used to strip it off would work too).

**Comment by damccorm** [comment]
Yeah, a convenience function there seems like it could be nice. For now, you can probably do something like:
```
var branchName = github.context.ref;
if (branchName.indexOf('/refs/heads/') > -1) {
  branchName = branchName.slice('/refs/heads/'.length);
}
```

**Comment by DanTup** [comment]
@damccorm in my case I'm just trying to use it in the workflow file rather than an action - I don't think I can put arbitrary JS in there?

```
          
      - name: Upload logs to Amazon S3
        run: dpl --provider=s3 --local-dir=".test_results" --upload-dir="${{ github.ref }}/${{ github.sha }}"
```

**Comment by damirstuhec** [comment]
@damccorm 

> ```
> var branchName = github.context.ref;
> if (branchName.indexOf('/refs/heads/') > -1) {
>   branchName = branchName.slice('/refs/heads/'.length);
> }
> ```

I tried that but the `branchName` is always `master`, even when the `issue_comment` is posted on another branch (PR).

Basically, my use case is a workflow that runs when a specific `issue_comment` is posted on a feature branch (PR) which will then trigger a CircleCI job for that branch through their API. Unfortunately, CircleCI only supports triggering the build by a branch name.

**Comment by DanTup** [comment]
@damirstuhec I don't know if it'll be populated for comments, but there's a `head_ref` and `base_ref` listed [here](https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#github-context). It says they're only populated for PR events, but I'm not sure exactly what that means.

**Comment by chrispat** [comment]
@damirstuhec as documented on: issues: triggers will always run on the default branch as issues don't really have a ref they are associated with.

**Comment by bryanmacfarlane** [comment]
Closing this out since @chrispat answered ^^ and not so much a toolkit issue.  Thanks!
